### ISSUE TITLE
test_backward_stepping_barrier_state not working

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#185]
The test `test_backward_stepping_barrier_state` within `test_z_backward_stepping.py` is no longer working (osl42). I would guess it is an issue with `wait_for_execution_engine_sync_counter`, as the test runs successfully if I slowly step through it in debug mode.

I'm however not sure what the root cause is. It could be that the issue is more general but only caused by certain circumstances within that test.

This is the first error message I get:

```
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 80, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/container_state.py", line 166, in model_changed
    super(ContainerStateModel, self).model_changed(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/state.py", line 90, in model_changed
    super(StateModel, self).model_changed(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/abstract_state.py", line 230, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/container_state.py", line 166, in model_changed
    super(ContainerStateModel, self).model_changed(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/state.py", line 90, in model_changed
    super(StateModel, self).model_changed(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/abstract_state.py", line 230, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/container_state.py", line 161, in model_changed
    changed_list._notify_method_before(self.state, cause, (self.state,), info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/support/wrappers.py", line 78, in _notify_method_before
    args, kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 537, in notify_method_before_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 467, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/state_machine.py", line 163, in root_state_model_before_change
    self.__send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/state_machine.py", line 291, in __send_root_state_notification
    self.state_machine._notify_method_before(self.state_machine, cause, (self.state_machine, ), info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/support/wrappers.py", line 78, in _notify_method_before
    args, kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 537, in notify_method_before_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 467, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/models/state_machine.py", line 242, in change_root_state_type
    if info.method_name != 'change_root_state_type':
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-10-13 09:37:59+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
More information:
- The exception stacktrace varies, the source is however always `RuntimeError: maximum recursion depth exceeded while calling a Python object`
- Interestingly, when raising the recursion limit from default 1000 to above 3000 (`
  sys.setrecursionlimit(3000)`), the test passes. Thus, there seems to be no infinite recursion. Yet, I cannot explain why such a high limit is required for this test.


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-10-14 10:36:38+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I cannot reproduce this on my computer so we somehow need a way to debug this.


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-10-20 13:58:37+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I switched to gaphas yesterday and I now get the error. Switching back to OpenGL and executing the test does not produce any error.


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-10-27 05:22:05+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Duplicate of #258, setting recursion limit reverted in 7f32762


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-12-19 16:41:30+00:00 (moved from RMC internal repository)
