### ISSUE TITLE
Menu bar test no longer running

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#211]
The menu bar test fail every time, in an early phase [when opening a state machine](https://rmc-github-server/common/rafcon/blob/develop/source/test/common/test_z_gui_menu_bar.py#L154), due to a warning:
`WARNING - rafcon.mvc.controllers.utils.tree_view_controller:  Iter has to be TreeIter -> handed argument is: None`
When I raise an exception instead of logging a warning, I get the following traceback:

```
Traceback (most recent call last):
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py", line 589, in selection_changed
    self.update_selection_self_prior()
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py", line 563, in update_selection_self_prior
    sm_selection, selected_model_list, sm_selected_model_list)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py", line 516, in iter_tree_with_handed_function
    iter_all_children(self.tree_store.get_iter_root(), function, function_args)
  File "/home_local/franzlst/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py", line 513, in iter_all_children
    raise RuntimeError()
RuntimeError
```

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-11-03 13:58:58+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
In some situations the tree view has no root iterator so the return is None. The issue is fixed by commit 71ee49fc79dc04fe. 


Originally created by @Rbelder  at 2016-11-07 14:26:31+00:00 (moved from RMC internal repository)
