### ISSUE TITLE
issue when dragging data flows

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#221]
On trying to drag a connected data_port to another location:
...

08:18:11:    ERROR - rafcon.mvc.mygaphas.tools:  An unexpected exception occurred while finalizing a connection: <rafcon.mvc.mygaphas.items.connection.ConnectionPlaceholderView object at 0x7fe1e54e4510> (KeyError)
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/decorators.py", line 137, in async_wrapper
    func(_args, *_kwargs)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/canvas.py", line 617, in update
    self.update_now()
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/decorators.py", line 167, in wrapper
    return func(_args, *_kwargs)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/canvas.py", line 660, in update_now
    dirty_items = sort(self._dirty_items, reverse=True)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/canvas.py", line 519, in sort
    return self._tree.sort(items, index_key='_canvas_index', reverse=reverse)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tree.py", line 208, in sort
    return sorted(nodes, key=attrgetter(index_key), reverse=reverse)
AttributeError: 'ConnectionPlaceholderView' object has no attribute '_canvas_index'
08:18:12:    ERROR - rafcon.mvc.models.state_machine:  path element UNTQDJ/JUTLNX of '[u'UNTQDJ', u'JUTLNX', u'HFRGHR']' could not be found root_state is active seismic network UNTQDJ
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/graphical_editor_gaphas.py", line 259, in _update_selection_from_gaphas
    self.model.selection.set(selected_models)
  File "/home_local/sebastian-brunner/develop/gtkmvc_dlr/gtkmvc/observable.py", line 49, in wrapper
    res = _func(_args, *_kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/selection.py", line 102, in set
    if self.__with_updates: self.__update()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/selection.py", line 122, in __update
    self.data_flows = self.get_data_flows()
  File "/home_local/sebastian-brunner/develop/gtkmvc_dlr/gtkmvc/observable.py", line 50, in wrapper
    self._notify_method_after(self, _func.__name__, res, args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc_dlr/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc_dlr/gtkmvc/model.py", line 574, in notify_method_after_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc_dlr/gtkmvc/model_mt.py", line 73, in __notify_observer__
    _args, *_kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc_dlr/gtkmvc/model.py", line 467, in **notify_observer**
    return method(_args, *_kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/state_editor/data_flows.py", line 383, in state_machine_selection_changed
    self.update_selection_sm_prior()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py", line 296, in update_selection_sm_prior
    tree_selection, selected_model_list, sm_selection, sm_selected_model_list = self.get_selections()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py", line 210, in get_selections
    sm_selection, sm_selected_model_list = self.get_state_machine_selection()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/state_editor/data_flows.py", line 377, in get_state_machine_selection
    sm_selection = self.model.get_sm_m_for_state_m().selection
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/models/abstract_state.py", line 179, in get_sm_m_for_state_m
    if sm_m.get_state_model_by_path(self.state.get_path()) is self:
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/models/state_machine.py", line 218, in get_state_model_by_path
    assert False
AssertionError

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-11-09 07:20:43+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The error happened again when moving an unconnected outcome. 


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-11-09 08:46:14+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
a different error:

/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/utils/tree_view_controller.py:191: GtkWarning: IA__gtk_tree_selection_get_selected_rows: assertion 'selection->tree_view != NULL' failed
  model, paths = self._tree_selection.get_selected_rows()
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/view.py", line 863, in do_event
    return self._tool.handle(event) and True or False
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tool.py", line 208, in handle
    return self._grabbed_tool.handle(event)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tool.py", line 126, in handle
    return self._dispatch(event)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tool.py", line 121, in _dispatch
    return bool(h(event))
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/tools.py", line 508, in on_motion_notify
    self.check_sink_item(self.motion_handle.move(pos, snap_distance), handle, item)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/tools.py", line 710, in check_sink_item
    self.disconnect_last_active_port(handle, connection)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/tools.py", line 724, in disconnect_last_active_port
    connection.reset_port_for_handle(handle)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/items/connection.py", line 20, in reset_port_for_handle
    self.reset_from_port()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/items/line.py", line 125, in reset_from_port
    self._handles.remove(self._from_waypoint)
ValueError: list.remove(x): x not in list
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/view.py", line 863, in do_event
    return self._tool.handle(event) and True or False
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tool.py", line 208, in handle
    return self._grabbed_tool.handle(event)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tool.py", line 126, in handle
    return self._dispatch(event)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/tool.py", line 121, in _dispatch
    return bool(h(event))
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/tools.py", line 508, in on_motion_notify
    self.check_sink_item(self.motion_handle.move(pos, snap_distance), handle, item)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/tools.py", line 710, in check_sink_item
    self.disconnect_last_active_port(handle, connection)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/tools.py", line 724, in disconnect_last_active_port
    connection.reset_port_for_handle(handle)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/items/connection.py", line 20, in reset_port_for_handle
    self.reset_from_port()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/mygaphas/items/line.py", line 123, in reset_from_port
    self.canvas.solver.remove_constraint(self._from_port_constraint)
  File "<decorator-gen-8>", line 2, in remove_constraint
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/state.py", line 66, in wrapper
    return func(_args, *_kwargs)
  File "/internal_path/common/foreign_packages/python-gaphas/0.7.2/osl42-x86_64/lib/python2.7/site-packages/gaphas/solver.py", line 487, in remove_constraint
    assert constraint, 'No constraint (%s)' % (constraint,)
AssertionError: No constraint (None)


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-11-09 09:15:42+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Fixed in branch merged in 9f5d6aba8b0f2795f5fe796344eb1f35f98c886d


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-11-15 12:34:15+00:00 (moved from RMC internal repository)
