### ISSUE TITLE
Copy of library state does not work

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#252]
Copy of library state does not work

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-12-02 12:42:04+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I cannot reproduce this behavior any more so I will close this issue.


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-12-06 09:05:26+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Ok I can reproduce it again:
Copy of a library state, which consists out of a hierarchy state with several execution states, into a container state does not work.


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-12-06 09:56:13+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Stacktrace:
Exception while calling callback methods for action "copy": 'NoneType' object has no attribute 'supports_saving_state_names'
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/shortcut_manager.py", line 136, in trigger_action
    ret = callback_function(key_value, modifier_mask)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/core/decorators.py", line 31, in func_wrapper
    return_value = func(_args, *_kwargs)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/controllers/graphical_editor_gaphas.py", line 197, in _copy_selection
    global_clipboard.copy(self.model.selection)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/clipboard.py", line 49, in copy
    self.__create_core_object_copies(selection, smart_selection_adaption)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/clipboard.py", line 378, in __create_core_object_copies
    self.model_copies = deepcopy(self.selected_models)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib64/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/library_state.py", line 55, in __deepcopy__
    return self.**copy**()
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/library_state.py", line 50, in **copy**
    state_m = AbstractStateModel.**copy**(self)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/abstract_state.py", line 126, in **copy**
    state_m = self.**class**(state, parent=None, meta=None, load_meta_data=False)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/library_state.py", line 35, in **init**
    self.state_copy = model_class(state.state_copy, parent=self)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/container_state.py", line 54, in **init**
    self.states[state.state_id] = model_class(state, parent=self, load_meta_data=load_meta_data)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/library_state.py", line 35, in **init**
    self.state_copy = model_class(state.state_copy, parent=self)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/container_state.py", line 54, in **init**
    self.states[state.state_id] = model_class(state, parent=self, load_meta_data=load_meta_data)
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/library_state.py", line 40, in **init**
    self.load_meta_data()
  File "/internal_path/common/packages/rafcon/0.8.2/lib/python2.7/rafcon/gui/models/library_state.py", line 86, in load_meta_data
    if self.state.get_sm_for_state().supports_saving_state_names:
AttributeError: 'NoneType' object has no attribute 'supports_saving_state_names'


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-12-06 14:38:40+00:00 (moved from RMC internal repository)
