### ISSUE TITLE
Maximum recursion depth reached

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#258]
When executing several state machine in a row the following error occurs:

Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 80, in **idle_callback
    method(_args, *_kwargs)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/controllers/state_machine_tree.py", line 135, in states_update
    overview = NotificationOverview(info, False, self.__class**.**name**)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/utils/notification_overview.py", line 47, in **init**
    if 'after' in info:
RuntimeError: maximum recursion depth exceeded while calling a Python object

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-12-06 12:49:53+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Probably related:

RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 80, in **idle_callback
    method(_args, *_kwargs)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/container_state.py", line 169, in model_changed
    super(ContainerStateModel, self).model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/state.py", line 90, in model_changed
    super(StateModel, self).model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/abstract_state.py", line 257, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/abstract_state.py", line 257, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/container_state.py", line 169, in model_changed
    super(ContainerStateModel, self).model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/state.py", line 90, in model_changed
    super(StateModel, self).model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/abstract_state.py", line 257, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/abstract_state.py", line 257, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/container_state.py", line 169, in model_changed
    super(ContainerStateModel, self).model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/state.py", line 90, in model_changed
    super(StateModel, self).model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/abstract_state.py", line 257, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/abstract_state.py", line 257, in model_changed
    self.parent.model_changed(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/container_state.py", line 166, in model_changed
    changed_list._notify_method_after(self.state, cause, None, (self.state,), info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 574, in notify_method_after_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer**
    _args, *_kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 467, in **notify_observer**
    return method(_args, *_kwargs)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/state_machine.py", line 183, in root_state_model_after_change
    self.**send_root_state_notification(model, prop_name, info)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/state_machine.py", line 301, in __send_root_state_notification
    self.state_machine._notify_method_after(self.state_machine, cause, None, (self.state_machine, ), info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 574, in notify_method_after_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer**
    _args, *_kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 467, in **notify_observer**
    return method(_args, *_kwargs)
  File "/internal_path/common/packages/rafcon/0.8.1/lib/python2.7/rafcon/gui/models/modification_history.py", line 513, in assign_notification_change_type_root_state_after
    if info.method_name != "root_state_change":


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2016-12-06 12:53:34+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Fixed in a23a9eb and 91cb4c2


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-12-19 16:37:46+00:00 (moved from RMC internal repository)
