### ISSUE TITLE
rafcon ln configuration 

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#317]
Dear RAFCON Team, 
 
Currently I am trying to start a normal empty rafcon gui from ln_manager.

Starting rafcon with a script works fine (so I assume it should be also possible from ln manager): 
```
#!/bin/bash 

eval `rmpm_do env --env-format embed_sh rafcon`
rafcon_start_gui
```

I tried multiple things to integrate it in my ln configuration file (see below), but failed. I guess, there might be just some little things missing. Maybe you can point to a easy solution? 

Thanks 
Korbi

In the ln configuration I tried **(1)** 

```
defines
rafcon_root: /internal_path/common/packages/rafcon/latest
include %(rafcon_root)/share/rafcon.inc.lnc
```
produces: 
```
could not execve()
python2.7 /internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/mvc/start.py  -o  -c  -g 
errno 2: No such file or directory
```

then  **(2)** 
```
pipe_include rmpm_do lnenv rafcon
process rafcon lnenv
node: main
use_template: software_common_rafcon_environment
command: rafcon_start_gui
```
which produces: 
```
process tests/rafcon lnenv started with pid 10842

could not execve()
rafcon_start_gui
errno 2: No such file or directory

process with pid 10842 terminated with retval: 2
```

finally I could start the racfon gui with calling the shell commands above in a start_rafcon script **(3)**: 
```
process rafcon start script
node: main
append environment PATH: /internal_path/common/packages/rafcon/0.8.3/bin:/internal_path/common/foreign_packages/pango/1.40.3/osl42-x86_64/bin:/home/f_soft/bin/osl42-x86_64:/home/f_soft/bin/osl42-x86_64:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/eclipse:/opt/TeXLive/latest/bin/x86_64-linux:/opt/quest/bin:/usr/sbin:/usr/sbin
command: %(CURDIR)/../../scripts/start_rafcon
```
unfortunately this produced the following error 
```
process tests/rafcon start script started with pid 10851

/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
15:42:23:    DEBUG - rafcon.core.config:  Configuration loaded from /home/nott_ko/.config/yaml_configuration/config.yaml
15:42:23:    DEBUG - rafcon.gui.config:  Configuration loaded from /home/nott_ko/.config/yaml_configuration/gui_config.yaml
/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/config.py:80: GtkWarning: IA__gdk_pango_context_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  context = tv.get_pango_context()
/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/config.py:80: PangoWarning: pango_context_set_font_description: assertion 'context != NULL' failed
  context = tv.get_pango_context()
/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/config.py:80: PangoWarning: pango_context_set_base_dir: assertion 'context != NULL' failed
  context = tv.get_pango_context()
/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/config.py:80: PangoWarning: pango_context_set_language: assertion 'context != NULL' failed
  context = tv.get_pango_context()
15:42:23:    DEBUG - rafcon.core.library_manager:  Initializing Storage object ...
15:42:23:    DEBUG - rafcon.core.execution.execution_status:  State machine status is set to STATE_MACHINE_EXECUTION_STATUS.STOPPED
15:42:23:    DEBUG - rafcon.core.execution.execution_engine:  State machine execution engine initialized
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/gtkgl/__init__.py:21: GtkWarning: IA__gdk_x11_display_get_xdisplay: assertion 'GDK_IS_DISPLAY (display)' failed
  from _gtkgl import *

(rafcon_start_gui:10859): GdkGLExt-WARNING **: Window system doesn't support OpenGL.
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.8.3/bin/rafcon_start_gui", line 14, in <module>
    from rafcon.gui.controllers.main_window import MainWindowController
  File "/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/controllers/main_window.py", line 23, in <module>
    from rafcon.gui.controllers.state_machines_editor import StateMachinesEditorController
  File "/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/controllers/state_machines_editor.py", line 19, in <module>
    from rafcon.gui.controllers.graphical_editor import GraphicalEditorController
  File "/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/controllers/graphical_editor.py", line 40, in <module>
    from rafcon.gui.views.graphical_editor import Direction
  File "/internal_path/common/packages/rafcon/0.8.3/lib/python2.7/rafcon/gui/views/graphical_editor.py", line 11, in <module>
    import gtk.gtkgl
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/gtkgl/__init__.py", line 21, in <module>
    from _gtkgl import *
RuntimeError: OpenGL is not supported

process with pid 10851 terminated with retval: 1
```

Originally created by nott-ko  (korbinian.nottensteiner@dlr.de) at 2017-03-28 13:49:32+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
We will talk in the car. :)

Originally created by @Rbelder  at 2017-03-28 16:23:06+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The reason why (1) and (2) are not working is an error in the lnc file, which points to 
`lib/python2.7/rafcon/mvc/start.py`
instead of
`lib/python2.7/rafcon/gui/start.py`
In addition, `python2.7` cannot be found. Furthermore, the `forward_x11` flag must be set. These are all issues that will be fixed with the next release.

Meanwhile, here is a working configuration:
```
pipe_include rmpm_do env --env-format ln rafcon

process RAFCON
use_template: rafcon_environment
node: localhost 
pass_environment: HOME, USER, DISPLAY
command: %(ifexists "/usr/bin/python2.7", "/usr/bin/python2.7", "/opt/python/python2.7/bin/python2.7") %(RAFCON_ROOT_PATH)/source/rafcon/gui/start.py
flags: no_error_on_stop, start_in_shell, forward_x11
ready_regex: Ready
```

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-03-29 07:04:39+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
See 749addd and a536250 for changes in the next release

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-03-29 07:49:58+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Perfect. Is working now:-) Thank you for the quick reponse!


Originally created by nott-ko  (korbinian.nottensteiner@dlr.de) at 2017-03-29 14:30:20+00:00 (moved from RMC internal repository)
