### ISSUE TITLE
RAFCON_INSTANCE_LOCK_FILE exception

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#326]
When existing RAFCON, I get the following exception:

```
Traceback (most recent call last):
  File "/home_local/franzlst/rafcon/source/rafcon/gui/start.py", line 316, in <module>
    main()
  File "/home_local/franzlst/rafcon/source/rafcon/gui/start.py", line 298, in main
    if os.path.exists(constants.RAFCON_INSTANCE_LOCK_FILE.name):
AttributeError: 'NoneType' object has no attribute 'name'
```

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-04-19 08:50:55+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
@franzlst: I have seen this failure yesterday the first time and only once too, but I could not reproduce it, can you do this and give me the procedure?

I think it has to do with a very short life time of a RAFCON instance.

Originally created by @Rbelder  at 2017-04-19 09:13:36+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
For me, it happens every time.

Nevertheless, I had a quick look at the code and I'm not so happy about it. You store a reference to a closed file handler in the `constants.py` file. Yet, a file handler is no constant. In addition you are never interested in the file handler, but only the name/path of the file. So why not just storing the path in `constants.py`? This would also prevent such an exception.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-04-19 09:19:40+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Yes that is a good argument. 

The reason why it is like this is most likly because I never refactored the Backup again after finish to debug the major behavoir. As usual the code evolved from an early state where the file handler was hold by the auto backup module it self, but as you very fast can understand it was a bad Idea, too.

I will fix it. So don't panic. ;)

More interesting to me is, why this failure occurs now but not in the past??? That is a very important question. What has changed in the last days that cause this failure? Why it happens in your case every time? We should answer this question in this issue, too!!!

Originally created by @Rbelder  at 2017-04-19 09:28:05+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I (think I) found the reason:

```python
if global_gui_config.get_config_value('AUTO_RECOVERY_LOCK_ENABLED'):
        constants.RAFCON_INSTANCE_LOCK_FILE = open(os.path.join(RAFCON_TEMP_PATH_BASE, 'lock'), 'a+')
        constants.RAFCON_INSTANCE_LOCK_FILE.close()
```

comes _before_ the loading of the user config:

```python
setup_mvc_configuration(user_input.config_path, user_input.gui_config_path, user_input.gui_config_path)
```

So for my setup, `AUTO_RECOVERY_LOCK_ENABLED` initially is `False`, later it is `True`.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-04-19 09:37:06+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Both sub-tasks finished. The lock file generation is moved to after the loading of gui_config.yaml and the the use of the option is refactored and the gui.utils.constants only holds a constants PATH for the actual instance.
Also the lock file generation and deletion is moved to the respective module. Additionally the lock file is directly added/removed if the flag is set True. 

The issue is closed.

Originally created by @Rbelder  at 2017-04-19 13:09:29+00:00 (moved from RMC internal repository)
