### ISSUE TITLE
gaphas selection error 

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#356]
Cannot select state after creating it:

Stackstrace:

DEBUG:gui.views.utils.editor:The editor style 'rafcon-dark' is not supported. Using the default 'classic'
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 257, in _update_selection_from_gaphas
    self.model.selection.set(selected_models)
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/gui/models/selection.py", line 126, in set
    self.__update(method_name='set')
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/gui/models/selection.py", line 169, in __update
    self.parent_signal.emit(msg_namedtuple)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/observable.py", line 100, in emit
    model.notify_signal_emit(name, arg)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 608, in notify_signal_emit
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.1/lib/python2.7/site-packages/gtkmvc/model.py", line 467, in __notify_observer__
    return method(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/gui/controllers/states_editor.py", line 515, in selection_notification
    self.activate_state_tab(state_machine_m.selection.get_states()[0])
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/gui/controllers/states_editor.py", line 460, in activate_state_tab
    page_id = self.add_state_editor(state_m)
  File "/home_local/sebastian-brunner/develop/ontology_plugin/python/rafcon_ontology/controllers/states_editor.py", line 74, in add_state_editor
    handler_id = state_editor_view['source_view'].get_buffer().connect('changed', self.script_text_changed,
AttributeError: 'NoneType' object has no attribute 'get_buffer'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-06-06 06:37:01+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
It does not happen in the current develop branch, so maybe it is related with not having release the correct gtkmvc version!  Please fix as soon as possible.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-06-06 06:40:29+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Ok sorry it is a problem of my plugin. I'll fix it. I also enabled the 0.10.1 again.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-06-06 07:52:11+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Without the plugin the version works fine.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-06-06 07:54:53+00:00 (moved from RMC internal repository)
