### ISSUE TITLE
error in execution history storage

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#357]
Error poped up when the execution history was clean via the "Clean History" button and "Run from selected state" was triggered.

Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/core/execution/execution_engine.py", line 192, in _wait_for_finishing
    self.__running_state_machine.join()
  File "/internal_path/common/packages/rafcon/0.10.1/source/rafcon/core/state_machine.py", line 142, in join
    if self._execution_histories[-1].execution_history_storage is not None:
IndexError: list index out of range

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-06-06 09:12:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
quit clear the condition check is wrong ... or do you think it is more complex?

Originally created by @Rbelder  at 2017-06-06 10:12:46+00:00 (moved from RMC internal repository)
