### ISSUE TITLE
State Editor does not work

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#388]
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 257, in _update_selection_from_gaphas
    self.model.selection.set(selected_models)
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/models/selection.py", line 126, in set
    self.__update(method_name='set')
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/models/selection.py", line 169, in __update
    self.parent_signal.emit(msg_namedtuple)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/observable.py", line 98, in emit
    model.notify_signal_emit(name, arg)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 808, in notify_signal_emit
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/controllers/states_editor.py", line 515, in selection_notification
    self.activate_state_tab(state_machine_m.selection.get_states()[0])
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/controllers/states_editor.py", line 460, in activate_state_tab
    page_id = self.add_state_editor(state_m)
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/controllers/states_editor.py", line 268, in add_state_editor
    state_editor_view = StateEditorView()
  File "/internal_path/common/packages/rafcon/0.10.3/source/rafcon/gui/views/state_editor/state_editor.py", line 71, in __init__
    self.outcomes_view.scrollbar_widget = self['outcomes_scroller']
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/view.py", line 209, in __getitem__
    raise KeyError(key)
KeyError: 'outcomes_scroller'

Originally created by doem-an  at 2017-07-28 15:23:56+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So I can reproduce the error in the master tag 0.10.3 but not on the develop branch. It is not a big wonder that this is the case because the master is close to 200 commits behind the develop branch.

We should merge the develop branch next week into the master and finish this. And we should include the pull request #375 for selection inside of libraries into this, too.



Originally created by @Rbelder  at 2017-07-28 17:09:35+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
If somebody likes to have the explanation for this issue and reason why it happens. With 0.10.* we stayed on the newest gtkmvc version by leaving it to python-gtkmvc==1.99 ... any version before has a hard coded python-gtkmvc==1.99.1 in its /internal_path/common/packages/rafcon/VERSION/rafcon.pt file. That is all and the rest are missing adjustment which are in the develop-branch to satisfy the newest gtkmvc version which is in rmpm. 

@sebastian-brunner and @franzlst don't be confused in the gitrepo this changes of the rafcon.pt files are not in because we needed only the fix on the rmpm svn-repo. We can make this consistent if you like, too. Therefore we have to commit like 20 tags again and respective everytime the change to the rafcon.pt file.

Originally created by @Rbelder  at 2017-07-28 17:39:12+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So the issue can be closed after the merge because fixes are already for weeks on the develop-branch.

Originally created by @Rbelder  at 2017-07-28 17:43:12+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
In the latest release (0.10.3), the problem is fixed.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-07-31 16:40:30+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Only to give some inside, we make also the gtkmvc version for the RAFCON version 0.10.3 fix to 1.99.1 instate of 1.99.* (what result in usage of gtkmvc version 1.99.2). With RAFCON version 0.11.* current develop branch will be merged again and the gtkmvc version will continue with 1.99, so 1.99.2 will be used.

Originally created by @Rbelder  at 2017-08-01 10:20:17+00:00 (moved from RMC internal repository)
