### ISSUE TITLE
Empty library root state without child states cause meta data resize problems with side effects in gaphas drawing

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#406]
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/controller.py", line 174, in _idle_register_view
    self.register_view(view)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 96, in register_view
    self.setup_canvas()
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 689, in setup_canvas
    self.add_state_view_for_model(self.root_state_m, rel_pos=(10, 10))
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/core/decorators.py", line 51, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 769, in add_state_view_for_model
    self.add_state_view_for_model(child_state_m, state_v, child_rel_pos, child_size, hierarchy_level + 1)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/core/decorators.py", line 51, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 755, in add_state_view_for_model
    self.add_state_view_for_model(state_m.state_copy, state_v, hierarchy_level=hierarchy_level + 1)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/core/decorators.py", line 51, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 769, in add_state_view_for_model
    self.add_state_view_for_model(child_state_m, state_v, child_rel_pos, child_size, hierarchy_level + 1)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/core/decorators.py", line 51, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 754, in add_state_view_for_model
    gui_helper_meta_data.scale_library_content(state_m)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/helpers/meta_data.py", line 423, in scale_library_content
    resize_factor = scale_meta_data_according_state(models_dict, fill_up=True)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/helpers/meta_data.py", line 579, in scale_meta_data_according_state
    left, right, top, bottom = get_boundaries_of_elements_in_dict(models_dict=models_dict)
  File "/internal_path/common/packages/rafcon/0.11.1/source/rafcon/gui/helpers/meta_data.py", line 254, in get_boundaries_of_elements_in_dict
    left = models_dict['scoped_variables'].items()[0][1].get_meta_data_editor(gaphas_editor)['inner_rel_pos'][0]
IndexError: list index out of range

Originally created by doem-an  at 2017-09-28 13:59:48+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
This happend while chaning the MAX_VISIBLE_LIBARARY_HIERACHY during runtime. I never saw this behavior when changing it in the config before the start of rafcon. 

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-09-29 07:57:54+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
@doem-an please add your gui_config.yaml for more details to this issue. And for reproduction reasons the library you have open and which you try to show the content of. Only a traceback is not a very nice bug report.

I can imagine that you maybe put `MAX_VISIBLE_LIBRARY_HIERARCHY=0` what cause still problems in the actual release combined with some meta data. If this is the case use `MAX_VISIBLE_LIBRARY_HIERARCHY=1` that is basically our zero. Is failure in very first implementation.

But general the failure in the traceback seems to be caused by not perfect implementation of the meta_data-module combined with a very unusual library that is tried to be scaled.

Originally created by @Rbelder  at 2017-09-29 09:59:38+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> This happend while chaning the MAX_VISIBLE_LIBARARY_HIERACHY during runtime. I never saw this behavior when changing it in the config before the start of rafcon.

`MAX_VISIBLE_LIBARARY_HIERACHY` forces a refresh of all state machines (it is in `keys_requiring_state_machine_refresh` of `rafcon.gui.config`), so changing it during runtime should cause any trouble.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-09-29 10:48:35+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
>, so changing it during runtime should cause any trouble.

So this part of the sentence gives sense with 'should not' ... so I think that is what you wanted to write. The answer is that it still can cause problems and therefore the traceback shows the problem directly. I talked to @sebastian-brunner and they used empty LibraryStates, so a ContainerState without scoped variables and child states as root states. 

I will save words and invest them in fixing the bug.

Originally created by @Rbelder  at 2017-09-29 11:07:49+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
issue is solved and already released (see revision 0.11.2).

Originally created by @Rbelder  at 2017-09-29 16:36:46+00:00 (moved from RMC internal repository)
