### ISSUE TITLE
strange error while loading state machine

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#436]
Error while loading state data: Data file not found: /home_local/sebastian-brunner/robust_efficient_robot_tasks/pick_object/pick_object_HFXWXK/meta.json
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.12.0/source/rafcon/core/storage/storage.py", line 402, in load_state_recursively
    state_info = load_data_file(path_core_data)
  File "/internal_path/common/packages/rafcon/0.12.0/source/rafcon/core/storage/storage.py", line 483, in load_data_file
    raise ValueError("Data file not found: {0}".format(path_of_file))
ValueError: Data file not found: /home_local/sebastian-brunner/robust_efficient_robot_tasks/pick_object/pick_object_HFXWXK/meta.json
10:03:11 ERROR - gui.helpers.state_machine: Error while trying to open state machine: 'NoneType' object has no attribute 'get_states_statistics'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-11-23 09:08:47+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Rafcon says it cannot find a meta.json, but rafcon should create one if it does not exist!?

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-11-23 09:09:26+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The problem was actually that, Andi did not pushed a state machine correctly (so now the state machine runs), but still this error is misleading/strange.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2017-11-23 09:10:43+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The issue for the misleading error message is line 358 of `storage.py`:
```state_machine.root_state = load_state_recursively(parent=state_machine, state_path=root_state_path)```

The root state is directly asserted, without checking the return value of `load_state_recursively`. This is `None`, if the data file is not found. The exception for the missing data file is caught in `load_state_recursively` (line 403) and `None` is returned instead of a state.

So either the return value should be checked or the exception caught somewhere else.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2017-11-23 11:52:38+00:00 (moved from RMC internal repository)

**Comment by JohannesErnst** [comment]
The function `load_state_recursively`, see https://github.com/DLR-RM/RAFCON/blob/80884aea4353cd9484a2f913e3425bbc7c5ab88e/source/rafcon/core/storage/storage.py#L411

was improved mulitple times over the last years and proper error messages are thrown if a state machine cannot be loaded. The previous error cannot be reproduced.
