### ISSUE TITLE
execution_log utils; backward compatibility

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#459]
Logfile to reproduce: /net/rmc-lx0089/home_local/public/rafcon_execution_log_pick-and-place-slc-at-table_2017-12-15-10-11-13.shelve

```
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.12.1/bin/execution_log_viewer.py", line 159, in <module>
    tvexample = BasicTreeViewExample(args.file)
  File "/internal_path/common/packages/rafcon/0.12.1/bin/execution_log_viewer.py", line 66, in __init__
    log_helper.log_to_collapsed_structure(self.hist_items)
  File "/internal_path/common/packages/rafcon/0.12.2/source/rafcon/utils/execution_log.py", line 188, in log_to_collapsed_structure
    execution_item[l] = call_item[l]
KeyError: 'semantic_data'

```

Originally created by SebastianRiedela  (Sebastian.Riedel@dlr.de) at 2017-12-21 12:21:11+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
see pull request

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-01-19 16:32:59+00:00 (moved from RMC internal repository)
