### ISSUE TITLE
state machines with libraries cannot be closed

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#479]
state machines with libraries cannot be closed.

Steps to reproduce:
Open the tutorials/99_bottles_or_beer_in_library
Try to close it

The following stracktrace occurs:

```
The result type is <type 'exceptions.AssertionError'> and the full notification 	'after': True
	'model': <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x7f05517978d0>
	'prop_name': state_machine_manager
	'instance': <rafcon.core.state_machine_manager.StateMachineManager object at 0x7f0551cbd8d0>
	'method_name': remove_state_machine
	'args': (<rafcon.core.state_machine_manager.StateMachineManager object at 0x7f0551cbd8d0>, 1)
	'kwargs': {}
	'result': No constraint (None)
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observable.py", line 48, in wrapper
    self._notify_method_after(self, _func.__name__, res, args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 775, in notify_method_after_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine_manager.py", line 107, in model_changed
    sm_m.prepare_destruction()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine.py", line 149, in prepare_destruction
    self.destruction_signal.emit()
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observable.py", line 101, in emit
    model.notify_signal_emit(name, arg)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 808, in notify_signal_emit
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 315, in state_machine_destruction
    self.canvas.get_view_for_model(self.root_state_m).remove()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/mygaphas/items/state.py", line 190, in remove
    child.remove()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/mygaphas/items/state.py", line 190, in remove
    child.remove()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/mygaphas/items/state.py", line 190, in remove
    child.remove()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/mygaphas/items/connection.py", line 54, in remove
    super(ConnectionView, self).remove()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/mygaphas/items/line.py", line 109, in remove
    self.canvas.solver.remove_constraint(self._from_port_constraint)
  File "<decorator-gen-8>", line 2, in remove_constraint
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/state.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/solver.py", line 487, in remove_constraint
    assert constraint, 'No constraint (%s)' % (constraint,)
AssertionError: No constraint (None)
```

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-02-22 07:46:20+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I will disable the current released version.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-02-22 07:47:04+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Also reloading does not work.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-02-22 07:48:15+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The problem only occurs for state machines, where the "show" flag is enabled and saved. This is also the reason why our unit tests do not fire. 

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-02-22 07:50:30+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The pull request #480 should fix this issue.

The issue occured under even more restricted conditions: That library who's content is shown requires a ScopedVariable with a connected data flow. ScopedVariables of libraries are not drawn, as they are only existing in their `state_copy`. Thus, data flows to these ports can also not be drawn.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-02-22 08:32:14+00:00 (moved from RMC internal repository)
