### ISSUE TITLE
Execution toolbar "run until state" is not working

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#495]
The failure is caused by  the following traceback:

```
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.4/source/rafcon/core/state_machine_manager.py", line 174, in active_state_machine_id
    raise AttributeError("Active state machine can not be changed because state machine execution is active.")
AttributeError: Active state machine can not be changed because state machine execution is active.
```

Sub-task:
* [x] fix the it and avoid to set the active state machine id that late

Thanks to @buss-kr for reporting the issue.

Originally created by @Rbelder  at 2018-03-02 14:26:49+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
It seems to be at least not that simple as the log looks like. I will try to reproduce it with more details in the log and the respective state machine baked. 

Originally created by @Rbelder  at 2018-03-02 14:56:39+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
But at the end it is a combination of session-restore which sets the `selected_state_machine_id` and our known cross-effects of it into the `active_state_machine_id`  (which is not set in this case) and its clinch that is not full solved and waits for the final refactoring to be solved fully. Thereby this issue is connected to issue #387, too.

The bug is quit bad because it results into a no more usable RAFCON instance, so it has to be restarted.

Originally created by @Rbelder  at 2018-03-02 15:12:19+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Thx for fixing it! Can you be more specific about what do mean with the "refactoring" you mentioned? If you cannot express it in 2 sentences, we can also discuss it in the next meeting.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-03-05 09:21:36+00:00 (moved from RMC internal repository)
