### ISSUE TITLE
rafcon freezes while opening a state machine

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#519]
There seems to be an error with the execution history. Happened the second time today, will update when I know how to reproduce.

```
2018-04-20 13:15:51:    DEBUG - rafcon.core.states.state:  Finished execution of ExecutionState with name 'load_distributions' and id 'INIT_ROS_NODE': Outcome 'aborted' [-1]
2018-04-20 13:18:01:    DEBUG - rafcon.core.state_machine_manager:  Remove state machine with id 18
2018-04-20 13:18:01:    DEBUG - rafcon.gui.models.state_machine_manager:  Delete state machine model for state machine with id 18
2018-04-20 13:18:02:    DEBUG - rafcon.core.state_machine_manager:  Remove state machine with id 17
2018-04-20 13:18:02:    DEBUG - rafcon.gui.models.state_machine_manager:  Delete state machine model for state machine with id 17
2018-04-20 13:18:03:    DEBUG - rafcon.gui.controllers.library_tree:  Opening library as state-machine from path '/internal_path/peter-lehner/libraries/rmpl/rafcon/rmpl/mix/update_distributions'
2018-04-20 13:18:03:    DEBUG - rafcon.core.storage.storage:  Loading state machine from path /internal_path/peter-lehner/libraries/rmpl/rafcon/rmpl/mix/update_distributions...
2018-04-20 13:18:03:    DEBUG - rafcon.core.storage.storage:  Load state recursively: /internal_path/peter-lehner/libraries/rmpl/rafcon/rmpl/mix/update_distributions/update_distributions_INIT_ROS_NODE
2018-04-20 13:18:03:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/libraries/rmpl/rafcon/rmpl/mix/update_distributions) has 1 states. (Max hierarchy level 1)
2018-04-20 13:18:03:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/libraries/rmpl/rafcon/rmpl/mix/update_distributions) has 0 transitions.
2018-04-20 13:18:03:    DEBUG - rafcon.core.state_machine_manager:  Add new state machine with id 19
2018-04-20 13:18:03:    DEBUG - rafcon.gui.models.state_machine_manager:  Add new state machine model ... 
2018-04-20 13:18:03:    DEBUG - rafcon.gui.models.state_machine_manager:  Create new state machine model for state machine with id 19
2018-04-20 13:18:03:    DEBUG - rafcon.gui.controllers.state_machines_editor:  Create new graphical editor for state machine with id 19
2018-04-20 13:18:03:  VERBOSE - rafcon.gui.controllers.graphical_editor_gaphas:  Time spent in init 0.00106310844421 seconds for state machine 19
2018-04-20 13:18:03:    ERROR - rafcon.gui.models.state_machine_manager:  The result type is <type 'exceptions.AttributeError'> and the full notification 	'after': True
	'model': <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x2aedb0cfe7d0>
	'prop_name': state_machine_manager
	'instance': <rafcon.core.state_machine_manager.StateMachineManager object at 0x2aedb0d1c610>
	'method_name': add_state_machine
	'args': (<rafcon.core.state_machine_manager.StateMachineManager object at 0x2aedb0d1c610>, <rafcon.core.state_machine.StateMachine object at 0x2aedd9cc3810>)
	'kwargs': {}
	'result': 'NoneType' object has no attribute 'get_state_machine'
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/observable.py", line 48, in wrapper
    self._notify_method_after(self, _func.__name__, res, args, kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 775, in notify_method_after_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.7/source/rafcon/gui/models/state_machine_manager.py", line 95, in model_changed
    self.selected_state_machine_id = sm_id
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/support/metaclasses.py", line 779, in _setter
    _inner_setter(self, val)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/support/metaclasses.py", line 741, in _setter
    self.notify_property_value_change(prop_name, old, val)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 700, in notify_property_value_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.7/source/rafcon/gui/controllers/execution_history.py", line 258, in notification_selected_sm_changed
    self.update()
  File "/internal_path/common/packages/rafcon/0.12.7/source/rafcon/gui/controllers/execution_history.py", line 306, in update
    self._store_expansion_state()
  File "/internal_path/common/packages/rafcon/0.12.7/source/rafcon/gui/controllers/execution_history.py", line 220, in _store_expansion_state
    state_machine = self.get_history_item_for_tree_iter(root_iter).state_reference.get_state_machine()
AttributeError: 'NoneType' object has no attribute 'get_state_machine'
2018-04-20 13:18:03:    ERROR - rafcon.gui.helpers.state_machine:  Error while trying to open state machine: 'NoneType' object has no attribute 'get_state_machine'
2018-04-20 13:18:03:  VERBOSE - rafcon.gui.controllers.graphical_editor_gaphas:  start setup canvas
2018-04-20 13:18:03:  VERBOSE - rafcon.gui.controllers.graphical_editor_gaphas:  Time spent in setup canvas 0.00791907310486 state machine 19
2018-04-20 13:18:04:    DEBUG - rafcon.core.execution.execution_engine:  Start execution engine ...
```

Originally created by @peter-lehner  at 2018-04-20 11:25:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Rico and me noticed this bug as well. Something is calling update in the execution_history, although the statemachine and the state_reference is already destroyed. I already commited a temporal fix for this in 7a28f3bef6c6685471. We will release it soon.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-04-20 11:46:00+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I do the release, today, and we keep track of this problem. And I think we still consider the issue as not solved because the fix is more a work around with debugging functionality.

Originally created by @Rbelder  at 2018-04-20 12:23:40+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Happened again just now. I opened the last history and afterwards tries to start the same statemachine agian:
```
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loading state machine from path /internal_path/moro/packages/pantilt_msgs/0.2.11/osl42-x86_64/indigo/rafcon/pantilt_msgs/get_position...
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Load state recursively: /internal_path/moro/packages/pantilt_msgs/0.2.11/osl42-x86_64/indigo/rafcon/pantilt_msgs/get_position/get_position_ORVJHQ
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/moro/packages/pantilt_msgs/0.2.11/osl42-x86_64/indigo/rafcon/pantilt_msgs/get_position) has 1 states. (Max hierarchy level 1)
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/moro/packages/pantilt_msgs/0.2.11/osl42-x86_64/indigo/rafcon/pantilt_msgs/get_position) has 0 transitions.
2018-05-09 11:54:36:    DEBUG - rafcon.execution_hooks.hooks:  load state machine WITHOUT hooks
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Load state recursively: /internal_path/peter-lehner/projects/omnirob/statemachines/manipulation/get current configuration/get_current_robot_configuration_IVFMYU/joint_state_QAUQAG
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loading state machine from path /internal_path/peter-lehner/projects/omnirob/statemachines/interface/status/joint_state...
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Load state recursively: /internal_path/peter-lehner/projects/omnirob/statemachines/interface/status/joint_state/joint_state_IIUURR
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/projects/omnirob/statemachines/interface/status/joint_state) has 1 states. (Max hierarchy level 1)
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/projects/omnirob/statemachines/interface/status/joint_state) has 0 transitions.
2018-05-09 11:54:36:    DEBUG - rafcon.execution_hooks.hooks:  load state machine WITHOUT hooks
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/projects/omnirob/statemachines/manipulation/get current configuration) has 9 states. (Max hierarchy level 4)
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/projects/omnirob/statemachines/manipulation/get current configuration) has 11 transitions.
2018-05-09 11:54:36:    DEBUG - rafcon.execution_hooks.hooks:  load state machine with hooks -> /internal_path/peter-lehner/projects/omnirob/statemachines/manipulation/get current configuration
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/projects/omnirob/statemachines/manipulation/check_current_configuration_for_collision) has 11 states. (Max hierarchy level 5)
2018-05-09 11:54:36:    DEBUG - rafcon.core.storage.storage:  Loaded state machine (/internal_path/peter-lehner/projects/omnirob/statemachines/manipulation/check_current_configuration_for_collision) has 15 transitions.
2018-05-09 11:54:36:    DEBUG - rafcon.execution_hooks.hooks:  load state machine WITHOUT hooks
2018-05-09 11:54:36:    DEBUG - rafcon.core.state_machine_manager:  Add new state machine with id 310
2018-05-09 11:54:36:    DEBUG - rafcon.gui.models.state_machine_manager:  Add new state machine model ... 
2018-05-09 11:54:36:    DEBUG - rafcon.gui.models.state_machine_manager:  Create new state machine model for state machine with id 310
2018-05-09 11:54:36:    DEBUG - rafcon.gui.models.library_state:  Do not initialize state copy Model of state: LibraryState with name 'get_current_scene' and id 'PSUNUW'
2018-05-09 11:54:36:    DEBUG - rafcon.gui.models.library_state:  Do not initialize state copy Model of state: LibraryState with name 'get_object_id' and id 'CHPXFC'
2018-05-09 11:54:36:    DEBUG - rafcon.gui.models.library_state:  Do not initialize state copy Model of state: LibraryState with name 'get_pose_from_object_to_object' and id 'YTILII'
2018-05-09 11:54:36:    DEBUG - rafcon.gui.controllers.state_machines_editor:  Create new graphical editor for state machine with id 310
2018-05-09 11:54:36:  VERBOSE - rafcon.gui.controllers.graphical_editor_gaphas:  Time spent in init 0.000370979309082 seconds for state machine 310
2018-05-09 11:54:36:     INFO - rafcon.gui.helpers.state_machine:  It took 0.244971036911 seconds to load 11 states with 5 hierarchy levels.
2018-05-09 11:54:36:  VERBOSE - rafcon.gui.controllers.graphical_editor_gaphas:  start setup canvas
2018-05-09 11:54:36:    DEBUG - rafcon.gui.controllers.graphical_editor_gaphas:  Hash has changed from bb9f1d04c3d269790d4628896f812306a83ca1b7b542efd2c666f8a2d5605558 to 3e41e96c84eaa0ac341428706aa7b80ae26c8814d3c8c1c3315077c00933eba5
2018-05-09 11:54:36:     INFO - rafcon.gui.controllers.graphical_editor_gaphas:  Opening the state machine caused some meta data to be generated, which will be stored  when the state machine is being saved.
2018-05-09 11:54:36:  VERBOSE - rafcon.gui.controllers.graphical_editor_gaphas:  Time spent in setup canvas 0.045835018158 state machine 310
2018-05-09 11:54:41:  VERBOSE - rafcon.gui.controllers.utils.tree_view_controller:  Difference between tree view selection: 
set([]) 
and state machine selection: 
set([<rafcon.gui.models.state.StateModel object at 0x7efbe2d8ad10>])
2018-05-09 11:54:45:  VERBOSE - rafcon.gui.controllers.utils.tree_view_controller:  Difference between tree view selection: 
set([]) 
and state machine selection: 
set([<rafcon.gui.models.state.StateModel object at 0x7efc02bae210>])
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/gui/controllers/state_machines_editor.py", line 186, in on_switch_page
    self.model.selected_state_machine_id = new_sm_id
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/support/metaclasses.py", line 779, in _setter
    _inner_setter(self, val)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/support/metaclasses.py", line 741, in _setter
    self.notify_property_value_change(prop_name, old, val)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 700, in notify_property_value_change
    self, prop_name, info)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/gui/controllers/execution_history.py", line 261, in notification_selected_sm_changed
    self.update()
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/gui/controllers/execution_history.py", line 330, in update
    self.insert_execution_history(tree_item, execution_history[1:], is_root=True)
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/gui/controllers/execution_history.py", line 389, in insert_execution_history
    tree_item = self.insert_history_item(current_parent, history_item, "Enter" if is_root else "Call")
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/gui/controllers/execution_history.py", line 355, in insert_history_item
    logger.error("This must never happen! Current history_item is {}".format(history_item))
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/core/execution/execution_history.py", line 394, in __str__
    return "CallItem %s" % (ScopedDataItem.__str__(self))
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/core/execution/execution_history.py", line 383, in __str__
    return "SingleItem %s" % (HistoryItem.__str__(self))
  File "/internal_path/common/packages/rafcon/0.12.9/source/rafcon/core/execution/execution_history.py", line 258, in __str__
    return "HistoryItem with reference state name %s (time: %s)" % (self.state_reference.name, self.timestamp)
AttributeError: 'NoneType' object has no attribute 'name'
```

Originally created by @peter-lehner  at 2018-05-09 09:57:59+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
@peter-lehner Have you opened multiple state machines? 

This seems to happen when the selection is set and the notification reaches the widget. 

Hope it is not blocking further use of RAFCON?

Originally created by @Rbelder  at 2018-05-09 10:42:14+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
There is some race condition going no here I think. Probably something like:
- the execution history updates the tree
- the user selects another state machine
- the new state machine doesn't have history items for the new state machine as it e.g. was not executed yet

I will have a closer look at it. Unfortunately I will be away for the next two weeks ...

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-05-09 12:05:59+00:00 (moved from RMC internal repository)
