### ISSUE TITLE
refreshing statemachine leads to error

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#528]
After clicking refresh selected state machine the following log is created.

08:58:25 DEBUG - execution_hooks.execution_hooks_script: resp: None.
08:58:28 DEBUG - core.state_machine_manager: Remove state machine with id 1
08:58:28 DEBUG - core.execution.execution_history: Closed log file /internal_path/project_omnirob/common/data/stash_data/rafcon/2018-05-24-08:53:45_rafcon_execution_log_pick-and-place-slc-at-table.shelve
08:58:28 DEBUG - core.execution.execution_history: Closed log file /internal_path/project_omnirob/common/data/stash_data/rafcon/2018-05-24-08:53:45_rafcon_execution_log_pick-and-place-slc-at-table.shelve
08:58:28 DEBUG - core.execution.execution_history: Closed log file /internal_path/project_omnirob/common/data/stash_data/rafcon/2018-05-24-08:53:45_rafcon_execution_log_pick-and-place-slc-at-table.shelve
08:58:28 ERROR - gui.models.state_machine_manager: The result type is <type 'exceptions.RuntimeError'> and the full notification 	'after': True
	'model': <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x7f99a1d49190>
	'prop_name': state_machine_manager
	'instance': <rafcon.core.state_machine_manager.StateMachineManager object at 0x7f99a2045d90>
	'method_name': remove_state_machine
	'args': (<rafcon.core.state_machine_manager.StateMachineManager object at 0x7f99a2045d90>, 1)
	'kwargs': {}
	'result': maximum recursion depth exceeded
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.10/source/rafcon/core/state_machine_manager.py", line 131, in remove_state_machine
    removed_state_machine.destroy_execution_histories()
  File "/internal_path/common/packages/rafcon/0.12.10/source/rafcon/core/state_machine.py", line 217, in destroy_execution_histories
    execution_history.destroy()
  File "/internal_path/common/packages/rafcon/0.12.10/source/rafcon/core/execution/execution_history.py", line 120, in destroy
    self._history_items[0].destroy()
  File "/internal_path/common/packages/rafcon/0.12.10/source/rafcon/core/execution/execution_history.py", line 268, in destroy

.........................

  File "/internal_path/common/packages/rafcon/0.12.10/source/rafcon/core/execution/execution_history.py", line 268, in destroy
    self.next.destroy()
RuntimeError: maximum recursion depth exceeded

Originally created by doem-an  at 2018-05-24 07:07:41+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The recursion seems to be connected with a big state machine which was already executed and the log is or was stored to the file system. The storing in this case seems to happen at the same time like the refresh maybe this is interconnected.

Originally created by @Rbelder  at 2018-05-24 08:45:36+00:00 (moved from RMC internal repository)
