### ISSUE TITLE
Build bot setup should be independent from network connection

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#546]
We have already a while problems with the network connection to the build bot PC and thereby or installation routine is failing in 1 or 2 times every 10 builds. Here respective traceback it is already known as the pandas error (but it seems to be an network issue):

```
Download error on https://pypi.python.org/simple/pandas/: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'pandas' (maybe misspelled?)
Download error on https://pypi.python.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or working download links found for pandas
Traceback (most recent call last):
  File "setup.py", line 173, in <module>
    zip_safe=True
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
    replace_conflicting=True,
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home_local/rmc-buildbot-slave/venv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 667, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pandas')
```

A solution could be to test the network connection first and then do or not do the installation routine. What do you think about it?

Originally created by @Rbelder  at 2018-05-30 09:18:40+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The actual test is invoked via `python setup.py test` (see `.buildbot.yaml`). Setuptools automatically tries to install the requirements first, i don't think there is a way to prevent this.

Maybe the virtual PyPi repository on Artifactory will solve this problem. Still, in this case, Artifactory requires a network connection. 

Edit: I remove the "bug" label, as this is no bug.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-07-18 11:40:11+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
We now use Jenkins, tox and the Artifactory PyPI proxy!

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2019-08-06 12:14:32+00:00 (moved from RMC internal repository)
