### ISSUE TITLE
Rafcon crash during reload

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#552]
2018-06-06 09:29:35:    ERROR - rafcon.gui.models.state_machine_manager:  The result type is <type 'exceptions.AttributeError'> and the full notification 	'after': True
	'model': <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x7f8422934190>
	'prop_name': state_machine_manager
	'instance': <rafcon.core.state_machine_manager.StateMachineManager object at 0x7f8422e32d90>
	'method_name': remove_state_machine
	'args': (<rafcon.core.state_machine_manager.StateMachineManager object at 0x7f8422e32d90>, 1)
	'kwargs': {}
	'result': 'NoneType' object has no attribute 'destroy_execution_histories'
Traceback (most recent call last):
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.11/source/rafcon/core/state_machine_manager.py", line 131, in remove_state_machine
    removed_state_machine.destroy_execution_histories()
AttributeError: 'NoneType' object has no attribute 'destroy_execution_histories'
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.12.11/source/rafcon/gui/controllers/state_machines_editor.py", line 419, in on_close_clicked
    remove_state_machine_m()
  File "/internal_path/common/packages/rafcon/0.12.11/source/rafcon/gui/controllers/state_machines_editor.py", line 372, in remove_state_machine_m
    self.model.state_machine_manager.remove_state_machine(state_machine_id)
  File "/internal_path/common/foreign_packages/python-gtkmvc/1.99.2/lib/python2.7/site-packages/gtkmvc/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.12.11/source/rafcon/core/state_machine_manager.py", line 131, in remove_state_machine
    removed_state_machine.destroy_execution_histories()
AttributeError: 'NoneType' object has no attribute 'destroy_execution_histories'

Originally created by doem-an  at 2018-06-06 07:32:04+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
How can removed_state_machine.destroy_execution_histories() and thus state_machine_manager.remove_state_machine() be called twice!?
There is some wrong observer behavior going on.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-06-06 07:49:35+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I think the error message from [here](https://rmc-github-server/common/rafcon/blob/develop/source/rafcon/core/state_machine_manager.py#L121) should have been printed before the traceback. 

@doem-an: Next time please also add the logger message before the trace back to help fixing the issue faster.

There is now a fix on the develop for this case and @sebastian-brunner will check if this is alright and can be continued. 
The possibility of this bug should have been there for already 4 month because @franzlst has changed the state machines controller in the way that the remove state machine method can be called twice in February.


Originally created by @Rbelder  at 2018-06-29 12:57:23+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
@Rbelder 
in the commit message of 49bc633  you say
> And do not let the state machines controller call the remove operation a second time if
the state machine is removed by refresh and thereby was already removed with the helper function.

What I get from this is that a reload causes the state machines to be deleted (by a helper function). Why is `remove_state_machine_m()` of the StateMachinesEditor  being called when this happens? I guess this is the root cause of the issue. The new check for existence in that method, which you added, is just a workaround. If you say this is caused by a change by me (can you point to the commit?) I can of course fix this by myselve.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-06-29 13:14:29+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
@franzlst I do not wanna annoy you and I thought it is too easy to find the commit. In this commit 292494e1 you refactored the remove_state_machine method and thereby the behavior of the method which is observing the state machines dict.

Generally it is right that there is a bigger problem in the code but this is not very small because it concerns the reuse of the remove_state_machine_of_tab in case of user click (state machine is still existing) and refresh (the state machine is already removed). Before the method could be used in this way because of the check `sm_id in state_machines`. So the one thing is a fix or work around and the other thing is a proper refactoring which includes secure case handling. So maybe we should write a test for this issue. 😄 

Originally created by @Rbelder  at 2018-06-29 13:30:55+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I wanted to fix this issue properly, but I don't know how to reproduce it. Can you tell me @Rbelder?

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-07-18 11:17:46+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Main problem is still that @doem-an has made a too little effort to describe the issue, e.g. the logger messages are not there except the traceback and no reproduction procedure. 

And I was searching for the problem and made some more robust line insertions which were avoiding this issue in the past. I am not fully sure if I could reproduce it in the past but I think I could. The hole thing was before my holidays and I would have to start now again, too. 

So sorry that I can not help directly. You have to uncomment the inserted lines and try to reproduce by your self. Tomorrow you are in the office so we can also talk directly about it. Usually I remember things when I am cycling home. 

The `return` after the error message is the real bug fix and the other line that removes the state machine the second time in the `close_clicked` method is the work around for the state machines editor controller.

Originally created by @Rbelder  at 2018-07-18 12:33:07+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So in fact you do not know whether the issue is fixed?

> The return after the error message is the real bug fix and the other line that removes the state machine the second time in the close_clicked method is the work around for the state machines editor controller.

What is the work around needed for if there is a real bug fix?

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-07-18 13:04:20+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
* [x] The issue on Core level is fixed 
* [ ] and the issue on GUI level is work around. 

That is what I already said. That is why the issue is still open and a bug.

The issue is caused by the GUI but should not crash the core. For now the user is not annoyed by the error messages because of the work around in the GUI.

In fact all I have done on GUI level is not directly fixing the issue but avoiding it and so I strongly think it is still there. So the issue has two peaces and one is done.

Originally created by @Rbelder  at 2018-07-18 14:21:21+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
"Believing" (or "Thinking") is not enough to hold an issue open. Moreover, this issue became much too indefinite. If there are new clear stack traces, the issue can be reopened.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-08-01 07:10:57+00:00 (moved from RMC internal repository)
