### ISSUE TITLE
Rafcon crash after running rafcon with example plugin

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#565]
1. Start rafcon with example plugin.
2. Open 99 Bottles of beer sm
3. start
4. stop
5. close RAFCON
6. see stacktrace

2018-07-24 12:32:53:    ERROR - rafcon.gui.models.state_machine_manager:  The result type is <type 'exceptions.AttributeError'> and the full notification 	'after': True
	'model': <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x7fe89b77f6d0>
	'prop_name': state_machine_manager
	'instance': <rafcon.core.state_machine_manager.StateMachineManager object at 0x7fe89b8753d0>
	'method_name': remove_state_machine
	'args': (<rafcon.core.state_machine_manager.StateMachineManager object at 0x7fe89b8753d0>, 1)
	'kwargs': {}
	'result': 'NoneType' object has no attribute 'register_observer'
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observable.py", line 48, in wrapper
    self._notify_method_after(self, _func.__name__, res, args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 775, in notify_method_after_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine_manager.py", line 107, in model_changed
    sm_m.prepare_destruction()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine.py", line 162, in prepare_destruction
    self.root_state = None
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/metaclasses.py", line 779, in _setter
    _inner_setter(self, val)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/metaclasses.py", line 741, in _setter
    self.notify_property_value_change(prop_name, old, val)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 700, in notify_property_value_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/share/examples/plugins/templates/gtkmvc_template_observer.py", line 108, in observe_root_state_assignments
    self.observe_model(info['new'])
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observer.py", line 351, in observe_model
    return model.register_observer(self)
AttributeError: 'NoneType' object has no attribute 'register_observer'
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/top_tool_bar.py", line 84, in on_close_button_clicked
    self.menu_bar_controller.on_quit_activate(None)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/menu_bar.py", line 434, in on_quit_activate
    avoid_shutdown = self.on_delete_event(widget, None, force=force)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/menu_bar.py", line 448, in on_delete_event
    gui_singletons.main_window_controller.prepare_destruction()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/main_window.py", line 638, in prepare_destruction
    rafcon.core.singleton.state_machine_manager.delete_all_state_machines()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/state_machine_manager.py", line 54, in delete_all_state_machines
    self.remove_state_machine(sm_id)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observable.py", line 48, in wrapper
    self._notify_method_after(self, _func.__name__, res, args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 775, in notify_method_after_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine_manager.py", line 107, in model_changed
    sm_m.prepare_destruction()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine.py", line 162, in prepare_destruction
    self.root_state = None
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/metaclasses.py", line 779, in _setter
    _inner_setter(self, val)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/metaclasses.py", line 741, in _setter
    self.notify_property_value_change(prop_name, old, val)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 700, in notify_property_value_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/share/examples/plugins/templates/gtkmvc_template_observer.py", line 108, in observe_root_state_assignments
    self.observe_model(info['new'])
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observer.py", line 351, in observe_model
    return model.register_observer(self)
AttributeError: 'NoneType' object has no attribute 'register_observer'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-07-24 10:34:41+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So the bug was not about running but closing the state machine. The error was created by our changes in the state machine model (while destruction) that is currently first assigning the root_state model None and then taking it out of the state_machines list of models in the state machine manager model.

I include the procedure described here into the test case of the template plugins and made the plugin robust again root_state model assignments to None and None to a new model what is needed to survive a root state type change.

Thanks for the report.

Originally created by @Rbelder  at 2018-07-24 14:35:11+00:00 (moved from RMC internal repository)
