### ISSUE TITLE
"Substitute library with template - keep state name" not working

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#570]
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/right_click_menu/state.py", line 317, in on_substitute_library_with_template_activate
    gui_helper_state_machine.substitute_selected_library_state_with_template(keep_name)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/helpers/state_machine.py", line 985, in substitute_selected_library_state_with_template
    substitute_selected_state(lib_state, as_template=True, keep_name=keep_name)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/helpers/state_machine.py", line 973, in substitute_selected_state
    gui_helper_state.substitute_state_as(selected_state_m, state, as_template, keep_name)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/helpers/state.py", line 507, in substitute_state_as
    state_m.state.name = target_state_m.state.name
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/decorators.py", line 52, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/states/execution_state.py", line 179, in name
    State.name.fset(self, name)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/decorators.py", line 52, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/observable.py", line 51, in wrapper
    self._notify_method_after(self, _func.__name__, e, args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/support/wrappers.py", line 91, in _notify_method_after
    args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 775, in notify_method_after_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc/model.py", line 613, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state.py", line 82, in model_changed
    self._mark_state_machine_as_dirty()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/abstract_state.py", line 425, in _mark_state_machine_as_dirty
    if self.get_state_machine_m().get_state_model_by_path(lib_state_path).is_about_to_be_destroyed_recursively:
AttributeError: 'NoneType' object has no attribute 'get_state_model_by_path'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-07-27 12:28:32+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I add a test for it and fixed the issue. I also use deepcopy instate of from_dict and can avoid the warnings printed while substitute as template.

Originally created by @Rbelder  at 2018-07-27 15:14:52+00:00 (moved from RMC internal repository)
