### ISSUE TITLE
Substitute State Fails

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#572]
Steps how to reproduce on simple state machine follows.

2018-08-01 09:18:20:    ERROR - rafcon.gui.controllers.graphical_editor_gaphas:  Cannot connect transition: Outcome with id '0' not found in state
2018-08-01 09:18:20:    ERROR - rafcon.gui.controllers.graphical_editor_gaphas:  Cannot connect transition: Outcome with id '0' not found in state
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/decorators.py", line 139, in async_wrapper
    func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/canvas.py", line 620, in update
    self.update_now()
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/decorators.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/canvas.py", line 663, in update_now
    dirty_items = sort(self._dirty_items, reverse=True)
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/canvas.py", line 520, in sort
    return self._tree.sort(items, index_key='_canvas_index', reverse=reverse)
  File "/home_local/sebastian-brunner/develop/gaphas/gaphas/tree.py", line 207, in sort
    return sorted(nodes, key=attrgetter(index_key), reverse=reverse)
AttributeError: 'TransitionView' object has no attribute '_canvas_index'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-08-01 07:19:37+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Finally I tried to reproduce this error but I could not. I used the baked state machine which you sent to me.
substitution_failing.tar (which I extracted and zipped again to insert it here)
[substitution_failing.zip](https://rmc-github-server/common/rafcon/files/81/substitution_failing.zip)

and run the `launch_rafcon_generated.sh` of the folder and tried to do substitute_as_template (keep_name as well as name from library). I also made common substitute with library operations which has had no problem. The commits I tested were, c935bb0ee (closest version to the 1st of August in develop), the version 0.12.17 (which fails with keep_name because of an other issue) and the current develop branch state commit 90525d59a. 

In any case I could not reproduce. The environment used is from the `rmpm_do env rafcon` and the local repo in the `PYTHONPATH`.

Further I could not run with `launch_rafcon_with_env_generated.sh` because of failing import of opengl with a RuntimeError that opengl is not supported. This maybe happens  because your system is of different version. 

Further the baked state machine is not using a very simple environment which maybe cause the problem by itself. E.g. your `LD_LIBRARY_PATH` has 8600 characters and includes pcl, ros and so on.

So the conclusion is that the reproduction procedure has to be clarified. 

@sebastian-brunner Check again if you can reproduce with what I used and create a visible description of this issue.

Ps.: Any bug reported like this with this kind of traceback and never updated description I will start to unlabel in future to not be a bug but a bad described issue, this foot steps of @doem-an do not need to be continued.

Originally created by @Rbelder  at 2018-08-14 14:50:09+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Have a look at: #576

Reopen it if necessary.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-08-16 11:31:42+00:00 (moved from RMC internal repository)
