### ISSUE TITLE
Opening a external source editor fails for a never set active state machine id

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#584]
When RAFCON restores a state machine on startup that contains an execution state, I cannot open an external editor for its source code. Following exceptions appears:

```
Traceback (most recent call last):
  File "/home_local/franzlst/rafcon/source/rafcon/gui/utils/external_editor.py", line 131, in open_externally_clicked
    open_file_in_editor(external_editor)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/utils/external_editor.py", line 93, in open_file_in_editor
    self.save_file_data(file_system_path)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/controllers/state_editor/source_editor.py", line 114, in save_file_data
    if sm.marked_dirty and not self.saved_initial:
AttributeError: 'NoneType' object has no attribute 'marked_dirty'
```

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-08-23 09:19:08+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I told @sebastian-brunner like two days ago about this bug. It is easy to solve and it was not introduced by me. I aspect only that is the reason why you assign it to me. I will fix it but Sebastian has to tell if this is working like he intended.

Anyway Sebastian was also not reacting after I have shown him the line.
sm = state_machine_manager_model.state_machine_manager.get_active_state_machine()

It has to be the selected state machine or better the state machine of the selected state I think.

Originally created by @Rbelder  at 2018-08-23 14:01:05+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So general the bug occurs not because of the restore state machine but because of never having run a state machine and thereby the active state machine id never was set.

Originally created by @Rbelder  at 2018-08-23 14:06:44+00:00 (moved from RMC internal repository)
