### ISSUE TITLE
ImportErrors when installing runnin RAFCON

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#6]
`/usr/lib/python2.7/site-packages/rafcon`

edit:
i then got: `ImportError: No module named gtkgl`
which I solved by installing: `python-gtkglext1`

now i get: 
````
2018-10-02 18:01:42:  WARNING - rafcon.gui.views.utils.editor:  Python module 'gtksourceview2' not found!
Traceback (most recent call last):
  File "/usr/local/bin/rafcon", line 9, in <module>
    load_entry_point('rafcon==0.12.24', 'gui_scripts', 'rafcon')()
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/start.py", line 323, in main
    setup_gui()
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/start.py", line 179, in setup_gui
    from rafcon.gui.controllers.main_window import MainWindowController
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/controllers/main_window.py", line 43, in <module>
    from rafcon.gui.controllers.states_editor import StatesEditorController
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/controllers/states_editor.py", line 28, in <module>
    from rafcon.gui.controllers.state_editor.state_editor import StateEditorController
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/controllers/state_editor/state_editor.py", line 33, in <module>
    from rafcon.gui.controllers.state_editor.source_editor import SourceEditorController
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/controllers/state_editor/source_editor.py", line 41, in <module>
    from rafcon.gui.views.state_editor.source_editor import SourceEditorView
  File "/usr/local/lib/python2.7/dist-packages/rafcon/gui/views/state_editor/source_editor.py", line 18, in <module>
    from rafcon.gui.views.utils.editor import EditorView, gtksourceview2
ImportError: cannot import name gtksourceview2
```

_Originally posted by @ct2034 in https://github.com/DLR-RM/RAFCON/issues/4#issuecomment-426327979_

**Comment by franzlst** [comment]
@ct2034:
Have you tried to follow the [installation preparations for Ubuntu 16.04](https://github.com/DLR-RM/RAFCON#installation-requirements-for-ubuntu-1604)? There it is mentioned that you need to install `python-gtkglext1`, `python-gtksourceview2` and some more packages manually before installing RAFCON.

Please tell us if that helps or if there are still complications!
