### ISSUE TITLE
NameError in StateEditorView

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#603]
Since one of the last releases of RAFCON we get the following error when we try to use our statemachine generator code. With RAFCON 0.12.21 everything was working fine... after the 5th of September we did not use RAFCON anymore. 

```
process all/shared/demo_planning/rafcon-service started with pid 2260

Traceback (most recent call last):
  File "/internal_path/project_smerobotics/rmpm/packages/rafcon-execution/0.2.0/share/ln/../../python/rafconlnservice.py", line 18, in <module>
    import rafconbuilder
  File "/internal_path/project_smerobotics/rmpm/packages/rafcon-execution/0.2.0/python/rafconbuilder.py", line 23, in <module>
    from rafconexec import init_rafcon
  File "/internal_path/project_smerobotics/rmpm/packages/rafcon-execution/0.2.0/python/rafconexec.py", line 17, in <module>
    from rafcon.gui.controllers.main_window import MainWindowController
  File "/internal_path/common/packages/rafcon/0.12.24/source/rafcon/gui/controllers/main_window.py", line 43, in <module>
    from rafcon.gui.controllers.states_editor import StatesEditorController
  File "/internal_path/common/packages/rafcon/0.12.24/source/rafcon/gui/controllers/states_editor.py", line 28, in <module>
    from rafcon.gui.controllers.state_editor.state_editor import StateEditorController
  File "/internal_path/common/packages/rafcon/0.12.24/source/rafcon/gui/controllers/state_editor/state_editor.py", line 38, in <module>
    from rafcon.gui.views.state_editor.state_editor import StateEditorView
  File "/internal_path/common/packages/rafcon/0.12.24/source/rafcon/gui/views/state_editor/state_editor.py", line 35, in <module>
    class StateEditorView(View):
  File "/internal_path/common/packages/rafcon/0.12.24/source/rafcon/gui/views/state_editor/state_editor.py", line 40, in StateEditorView
    _('Source'): constants.ICON_SOURCE,
NameError: name '_' is not defined

process with pid 2260 terminated with retval: 1

```

Originally created by nott-ko  (korbinian.nottensteiner@dlr.de) at 2018-09-20 11:00:27+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
You need to insert the following into your code, _before_ you import the `MainWindowController` and `View`:

```python
from rafcon.utils.i18n import setup_l10n
setup_l10n()
```

I will think about whether this should be done automatically.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-09-20 11:04:34+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Thanks for the quick answer! Adding this two lines to our code solved the issue 

Compare: 
https://rmc-github-server/proj-rm-smerobotics/rafcon-execution/commit/009c6077976ee2f41143d7540f23d871a0b2b9a6


Originally created by nott-ko  (korbinian.nottensteiner@dlr.de) at 2018-09-20 11:21:06+00:00 (moved from RMC internal repository)
