### ISSUE TITLE
Gaphas stable gkt3 release python2 and python3 compatible

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#628]
We need to enforce a stable gaphas release. At the moment the [master branch](https://github.com/gaphor/gaphas) is again not stable.

The last stable commit is [636424](https://github.com/gaphor/gaphas/commit/636424) what is currently 3 commits behind the master-HEAD at `ff38940f`.

At the moment we have two options from my perspective to directly continue with:
1. The easiest solution to this is to ask the gaphas maintainer `gaphor` to 
    - create a develop branch and reset the master and release the master 
    - or to simple tag the last stable commit and release it. 

2. We also can work around the hole situation for the first trail version for internal testing purpose by creating an internal release in rmpm and then release a RAFCON version that depends on it.

What is your opinion about this?

Originally created by @Rbelder  at 2018-11-22 16:55:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Why do you think is the current master not stable? Do you have issues with it?

I pushed the developers to release gaphas already some days ago: https://github.com/gaphor/gaphas/pull/28

They are currently trying to test RAFCON with gaphas, but cannot [because of missing dependencies](https://github.com/DLR-RM/RAFCON/issues/5).

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-11-23 07:38:25+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> Why do you think is the current master not stable? Do you have issues with it?

Because I have pulled the last master version and run my gtk3 environment with our current RAFCON develop branch (happens also with older versions) and it crash as follows, see below.

The last changes on the gaphas master are made 3 days ago. So please test it after you pulled the master.

Originally created by @Rbelder  at 2018-11-23 08:32:31+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Forgot the traceback:
```

2018-11-23 09:18:22:    DEBUG - rafcon.core.library_manager:  Initializing Storage object ...
2018-11-23 09:18:22:    DEBUG - rafcon.core.execution.execution_status:  State machine status is set to STATE_MACHINE_EXECUTION_STATUS.STOPPED
2018-11-23 09:18:22:    DEBUG - rafcon.core.execution.execution_engine:  State machine execution engine initialized
2018-11-23 09:18:22:    DEBUG - rafcon.start.gui:  Font 'DIN Next LT Pro' found
2018-11-23 09:18:22:    DEBUG - rafcon.start.gui:  Font 'FontAwesome' found
2018-11-23 09:18:22:     INFO - rafcon.start.gui:  Installing GTKSourceView style 'rafcon-dark.xml' to /home/Rbelder/.local/share/gtksourceview-3.0/styles
2018-11-23 09:18:22:     INFO - rafcon.start.gui:  Installing GTKSourceView style 'rafcon.xml' to /home/Rbelder/.local/share/gtksourceview-3.0/styles
2018-11-23 09:18:22:    DEBUG - rafcon.core.config:  Configuration loaded from /home/Rbelder/.config/rafcon/config.yaml
2018-11-23 09:18:22:    DEBUG - rafcon.core.library_manager:  Initializing LibraryManager: Loading libraries ... 
2018-11-23 09:18:22:    DEBUG - rafcon.core.library_manager:  Adding library root key 'spacebotcup' from path '/net/notos/home_local/dark_room/in_progress/statemachines/spacebotcup'
2018-11-23 09:18:22:    DEBUG - rafcon.core.library_manager:  Adding library root key 'kontur' from path '/home/Rbelder/projects/kontur2.2/software/state_machines/state_machines'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'robex' from path '/net/notos/home_local/dark_room/in_progress/statemachines/robex'
2018-11-23 09:18:23:  WARNING - rafcon.core.library_manager:  Configured path for library root key 'calibration_common' does not exist: /home/f_mobil/omnirob_rafcon_state_machines/calibration_common
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'slam' from path '/net/notos/home_local/dark_room/in_progress/statemachines/slam'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'manipulation' from path '/net/notos/home_local/dark_room/in_progress/statemachines/manipulation'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'world' from path '/net/notos/home_local/dark_room/in_progress/statemachines/world'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'ros' from path '/net/notos/home_local/dark_room/in_progress/statemachines/ros'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'unit_test_state_machines' from path '/net/notos/home_local/dark_room/taskcontrol/tests/assets/unit_test_state_machines'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'calibration' from path '/net/notos/home_local/dark_room/in_progress/statemachines/calibration'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'generic' from path '/internal_path/common/packages/rafcon/0.12.25/share/libraries/generic'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'links_and_nodes' from path '/net/notos/home_local/dark_room/in_progress/statemachines/links_and_nodes'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'exploration' from path '/net/notos/home_local/dark_room/in_progress/statemachines/exploration'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'k2aci_rafcon_adapter' from path '/net/notos/home_local/dark_room/in_progress/statemachines/k2aci_rafcon_adapter'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'navigation' from path '/net/notos/home_local/dark_room/in_progress/statemachines/navigation'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Adding library root key 'vision' from path '/net/notos/home_local/dark_room/in_progress/statemachines/vision'
2018-11-23 09:18:23:    DEBUG - rafcon.core.library_manager:  Initialization of LibraryManager done
2018-11-23 09:18:23:    DEBUG - rafcon.gui.config:  Configuration loaded from /home/Rbelder/.config/rafcon/gui_config.yaml
2018-11-23 09:18:24:    DEBUG - rafcon.gui.runtime_config:  Configuration loaded from /home/Rbelder/.config/rafcon/runtime_config.yaml
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/taskcontrol/bin/rafcon", line 390, in <module>
    main()
  File "/net/notos/home_local/dark_room/taskcontrol/bin/rafcon", line 350, in main
    setup_gui()
  File "/net/notos/home_local/dark_room/taskcontrol/bin/rafcon", line 181, in setup_gui
    from rafcon.gui.controllers.main_window import MainWindowController
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/controllers/main_window.py", line 44, in <module>
    from rafcon.gui.controllers.state_machines_editor import StateMachinesEditorController
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/controllers/state_machines_editor.py", line 50, in <module>
    from rafcon.gui.views.graphical_editor_gaphas import GraphicalEditorView as GraphicalEditorGaphasView
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/views/graphical_editor_gaphas.py", line 19, in <module>
    from gaphas import tool
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/__init__.py", line 28, in <module>
    from .canvas import Canvas
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 43, in <module>
    from gaphas import solver
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/solver.py", line 60, in <module>
    class Variable(object):
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/solver.py", line 87, in Variable
    strength = reversible_property(lambda s: s._strength, _set_strength)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/state.py", line 153, in reversible_property
    spec = inspect.getfullargspec(fset)
AttributeError: 'module' object has no attribute 'getfullargspec'
```


Originally created by @Rbelder  at 2018-11-23 08:34:13+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I asked the developers to fix it: https://github.com/gaphor/gaphas/commit/16d1264a6bdd2c11381e47cc72036b9c6e09d854#commitcomment-31403470

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-11-23 08:49:26+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So I changed the name of the issue to cover the goal we have to provide a python2 and python3 usable gtk3 version of RAFCON.

Originally created by @Rbelder  at 2018-11-23 09:14:39+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Gaphas 1.0.0 (RC) [has been released](https://github.com/gaphor/gaphas/releases/tag/1.0.0rc1).

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-05 07:59:22+00:00 (moved from RMC internal repository)
