### ISSUE TITLE
Cut of multiple states creates various problems

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#631]
Procedure:
- create a state machine 
- add two states
- select both states and cut them

Mostly the error is not fully deterministic. Generally in 9 of 10 cases something happens e.g.:
- delete or creation of state editor tab fails
- if the states are ES mostly the states editor can not access the source_view because the `model.state is None`
- for CS kind of states other peaces of the state editor do not have reference of state
- gaphas can not access the model.state.`method` because `model.state is None`

The reason is most likely that after the gtk3/python3 refactoring the selection is not unset or the widgets can not handle the remove of the state very well.

Originally created by @Rbelder  at 2018-11-27 13:30:18+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I have to leave now, but I wanted to give an update on what I have found out just now. I _think_ the problem is the `StatesEditor` itself.

I created the state machine as you specified and restarted RAFCON, so that the state machine is restored, but no state is selected and no StateEditor is opened. If you hold <Shift> and draw the selection around the child states, they get selected, but no StateEditor is opened. If you now cut the states, the StatesEditor nevertheless wants to destroy the page of the state, which of course fails.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-11-30 14:43:48+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
That is a good hint. Generally the states editor is only generating a state editor if exact one state is selected. Maybe this destruct in any case of destruction came into place by gtk3/python3 refactoring.

Originally created by @Rbelder  at 2018-12-03 10:49:09+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> the states editor is only generating state editor if exact one state is selected

I'm a bit further now. This fact plays a role here. The states are deleted one after another and thus removed from the selection one after another. If there is only one state left, the corresponding state editor is created. However, before `register_view` is called, the state is already removed.

This is a more general problem. A state can be removed before views related to it are fully constructed. At some points, we have checks for this, at others we don't. 

I will see if I can fix this.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-03 11:27:29+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I am quiet sure, in the past, the state editor or the extended controller could stand this and was able to overcome this.

> I will see if I can fix this.

So I will leave it to you for, now.

Originally created by @Rbelder  at 2018-12-03 11:31:22+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I have found a relative simple solution: Before the destruction signal of the state machine and state model is emitted, I inserted a `wait_for_gui`. This ensures that the GUI is fully constructed before the models are destructed. See ea615baa09eed2ba30e6fde9bdd39393becd6b3e in the `fix_issue_631_*` branch.

Now, the `test_recent_opened_state_machine_list` test is no more running, only when executed solely. @Rbelder: Could you have a look at this? I think this will be related to your code.

First there is an error
```ERROR - rafcon.gui.helpers.state_machine:  Error while trying to open state machine: Provided path doesn't contain a valid state machine: /tmp/rafcon-franzlst/19964/unit_tests/tmp_RZhEf```
After some more log statements, a second error appears:
```ERROR - rafcon.utils.log:  Unexpected error
Traceback (most recent call last):
  File "/home_local/franzlst/rafcon/source/rafcon/utils/log.py", line 143, in wrapper
    return function(*args, **kwargs)
  File "/home_local/franzlst/rafcon/tests/gui/test_recently_open.py", line 238, in trigger_gui_signals
    assert number_of_open_sm == len(sm_manager_model.state_machines) + 1
AssertionError: assert 5 == (5 + 1)
 +  where 5 = len({96: <rafcon.gui.models.state_machine.StateMachineModel object at 0x7fc96263fb...: <rafcon.gui.models.state_machine.StateMachineModel object at 0x7fc962a9f6d0>})
 +    where {96: <rafcon.gui.models.state_machine.StateMachineModel object at 0x7fc96263fb...: <rafcon.gui.models.state_machine.StateMachineModel object at 0x7fc962a9f6d0>} = <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x7fc97343bb50>.state_machines
```


> I quiet sure, in the past, the state editor or the extended controller could stand this and was able to overcome this.

The StatesEditor cannot withstand this, the StateEditor neither can, due to some lines in the Transitions- and DataFlowControllers, which might have been added during the porting to GTK3.

I hope with my changes, this won't be necessary in the future.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-03 12:24:23+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I also thought about a "wait for gui" to solve this issue but more on the level of the GUI which is creating the issue not the model which is generally fine. 

So basically this is creates a workaround in the model which fix the GUI. 

I really do not know if I like this. The destruction signal is thought to be used to let every GUI element handle this issue for its own. That we have this issue now shows us only, that this is still not done. Also the states editor could observe operations which are complex to not waste resources. At this point we have to admit that we already have a scaling problem.

I think the issue is similar to the gtk3 project note about destruction while running a state machine. And at this point I think we changed the destruction to destruct fully and this seems very likely the source of this problem. I would think about it ones more before mixing things up like this (and most likely create a work around that maybe comes back to use as deadlock).

Originally created by @Rbelder  at 2018-12-03 12:57:16+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I think this is not really a workaround, but a simple solution for a complex problem related to asynchronous events.

Models are "on the level of the GUI".

As far as I can remember, the destruction signal was originally introduced so that observers of an element are informed about the element's destruction _without_ having to observe the parent. I don't think that the destruction signal can be used to fix this issue. The problem that occurred here also was not only related to the fact that a `view` was accessed in he `destroy` handler, but also that the `model` was accessed in the `register_view` handler, where we never have a check for.

I also don't think this is a scaling problem. The problem arises from the asynchronous architecture.

> I think the issue is similar to the gtk3 project note about destruction while running a state machine.

Can you point to the note you are talking about? I cannot remember it.

If you have a better solution, I am open for it (please use a separate branch, though).

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-03 13:09:23+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> I also don't think this is a scaling problem. The problem arises from the asynchronous architecture.

I have not said it is a scaling problem but if we wait for the GUI we create potentially more of them and creating an state editor in a situation were this is not needed means we are waste cpu time.

> Can you point to the note you are talking about? I cannot remember it.

There is only one note in the project and it is in the needed open task section in the left column.

> If you have a better solution, I am open for it (please use a separate branch, though).

I will give it a trail.

Originally created by @Rbelder  at 2018-12-03 15:44:07+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So the trail can be found in branch fix_631_*. I continued with your fixes and skipped the wait for gui. I introduced an explicit handling of complex actions like it is known from the state machine editor hereby I also reused/duplicated lines of code, for now. 

Generally spoken the selection pattern is not fully defined and the widgets have not one handling of changes in selection. I choose this way to introduce explicit handling which is thought to be improved do improve performance.

I would merge it like it is and continue refactoring of selection and complex actions from this point on. E.g. should all operations that are not atomic be complex actions (e.g. multiple remove of elements) to have exact one update/reaction of the GUI for one user action.

Originally created by @Rbelder  at 2018-12-04 07:50:28+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So in this issue there was an interesting situation. If I was skipping the encapsulation of cut with state action signals this clinch was not happening. At this point we have to take attention to the fact that the states editor was not handling this signal and the sub-widgets not the cut action so the effect should be zero. 
I think other widgets which were doing or not doing the handling of this signal notification were creating timing issues because of missing encapsulation.

To enforce the finishing of GUI updates while a destruction of models is clearly a workaround especially if the models are most likely destroyed in the background in an separate threat, in the future.

Note: forgot a not in the signal description.

Originally created by @Rbelder  at 2018-12-04 07:59:05+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> So the trail can be found in branch fix_631_*. I continued with your fixes and skipped the wait for gui.

Why do you do that? I explicitly asked you to open a separate branch. Instead, you reuse the branch and even _delete_ of mine using a _force push_! Do you want to force your solution by deleting code of others, making it impossible to compare the two solutions?

> Generally spoken the selection pattern is not fully defined and the widgets have not one handling of changes in selection.

What is not fully defined? In what way do widgets handle the selection differently?

I agree that in this case it makes sense to not create a state editor in the first place. Nevertheless, I think your fix is only a fix for this special situation and not a generic solution for cases were states are deleted before corresponding views are created. Therefore, I vote for at least having a discussion for introducing the `wait_for_gui` before deleting models.

> hereby I also reused/duplicated lines of code, for now.

> I would merge it like it is and continue refactoring of selection and complex actions from this point on. 

Why do you want add code of which you know yourself that it needs refactoring? Could you please fix your code first and not postponing this to sometime later?

> So in this issue there was an interesting situation.

Sorry, but I cannot follow your situation. Could you rephrase it?

> the models are most likely destroyed in the background in an separate threat, in the future.

We don't live in the future. We need to handle the situation as it is now. Furthermore, I cannot remember that we have ever talked about something like this.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-04 10:59:16+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> Why do you do that?

Read carefully! It is a different branch!

> What is not fully defined? In what way do widgets handle the selection differently?

E.g. that not every widget that needs it care for complex actions explicitly.

> Therefore, I vote for at least having a discussion for introducing the wait_for_gui before deleting models.

That can be an action that the controller it self can perform but not the model. MVC has encapsulation which should be hold as long as possible and the order is core-model-controller-view or do you propose it different?

> Why do you want add code of which you know yourself that it needs refactoring? Could you please fix your code first and not postponing this to sometime later?

here you start only to argument because you want to argument ... so I stop to answer verbose. ;)

Originally created by @Rbelder  at 2018-12-04 12:03:56+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Could we dicuss this in the next meeting? I have the feeling that this won't lead anywhere.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-12-04 14:59:38+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
We now temporarily used Franz solution, although your one is nicer in the long term. To make all tests run we had to comment out two asserts in the recently_opened test. These asserts have to be fixed before closing this issue.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-12-17 16:02:50+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
> We now temporarily used Franz solution, although your one is nicer in the long term. To make all tests run we had to comment out two asserts in the recently_opened test. These asserts have to be fixed before closing this issue.

You never merged the fix of Franz into the develop branch. Now, the failure also was not occurring that frequently as before.

I fixed the problems in the pull-request and it can be merged, now.

Originally created by @Rbelder  at 2019-01-10 10:48:41+00:00 (moved from RMC internal repository)
