### ISSUE TITLE
Exception while closing and stopping a running state machine tab at once

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#637]
The initial mentioned notes is now transformed into #636 and the traceback already looks a bit different. 

There are two ways to reproduce different failures (but I will keep them here together because one is minor):
- create a new state machine
- add a state and set it as start state
- execute the state machine
- now there are two ways:
 - [ ] `1.` close the tab while saying stop execution (major)
 - [ ] `2.` close the main window while also saying stop execution (minor)

`1.` The major error is that the execution history is not written/created so the execution not stopped before the execution history is destroyed. So the state machine is started to be destroyed before the state machine has been stopped, see traceback.

```
13:49:46 ERROR - core.execution.execution_history: Exception: invalid operation on closed shelfTraceback (most recent call last):
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/core/execution/execution_history.py", line 62, in store_item
    self.store[native_str(key)] = value
  File "/usr/lib64/python2.7/shelve.py", line 133, in __setitem__
    self.dict[key] = f.getvalue()
  File "/usr/lib64/python2.7/shelve.py", line 79, in closed
    raise ValueError('invalid operation on closed shelf')
ValueError: invalid operation on closed shelf
13:49:46 DEBUG - core.execution.execution_history: Closed log file /home_local/Rbelder/log/rafcon/2018-12-05-13:49:42_rafcon_execution_log_new-root-state.shelve
13:49:46 ERROR - core.states.hierarchy_state: HierarchyState with name 'new root state' and id 'OQPIVW' [1 child states] had an internal error: 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/core/states/hierarchy_state.py", line 137, in run
    return self._finalize_hierarchy()
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/core/states/hierarchy_state.py", line 280, in _finalize_hierarchy
    self.execution_history.push_return_history_item(self, CallType.CONTAINER, self, self.output_data)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/core/execution/execution_history.py", line 208, in push_return_history_item
    return self._push_item(last_history_item, return_item)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/core/execution/execution_history.py", line 165, in _push_item
    self._history_items.append(current_item)
AttributeError: 'NoneType' object has no attribute 'append'
```

`2.` The traceback for the main window is minor and shows that the main window controller does not disconnects or is not yet disconnected from notification but set the view to None (means destroys it).

```
(start.py:15359): Gtk-CRITICAL **: _gtk_accel_group_detach: assertion 'g_slist_find (accel_group->priv->acceleratables, object) != NULL' failed
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 79, in __idle_callback
    method(*args, **kwargs)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/state_machine.py", line 188, in root_state_model_before_change
    self._send_root_state_notification(model, prop_name, info)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/state_machine.py", line 318, in _send_root_state_notification
    self.state_machine._notify_method_before(self.state_machine, cause, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_before'
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 79, in __idle_callback
    method(*args, **kwargs)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/state_machine.py", line 201, in root_state_model_after_change
    self._send_root_state_notification(model, prop_name, info)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/state_machine.py", line 320, in _send_root_state_notification
    self.state_machine._notify_method_after(self.state_machine, cause, None, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_after'
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 79, in __idle_callback
    method(*args, **kwargs)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/controllers/main_window.py", line 359, in model_changed
    self.view['execution_status_label'].set_text(label_string)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Originally created by @Rbelder  at 2018-12-05 12:55:21+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Maybe we should create a test to cover this.

Originally created by @Rbelder  at 2018-12-05 13:07:51+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
In what sense is your second (i.e. the minor) case different from issue #636 ?

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-12-06 09:02:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
In #636 the aim is to keep the state machine running but it is destroyed. 

Here we try to stop a state machine and to destroy it directly afterwards but that fails because the state machine is destroyed before fully stopped. That is generally a big difference. Also the traceback is generally very different. Here e.g. we have an error in the main window that thinks a tab is still there. Also it thinks the execution has already stopped so it can destroy but the notifications are still running while the destructions are on there way. 

While writing this it came to my mind that the only thing in common is maybe that the gtkmvc merge of the gtk3 branch of gtkmvc created different notification forwarding or timings. Maybe we should not try to fix this issues first on RAFCON site but investigate if the threading has changed within gtkmvc. So which call and notification paths has changed in RAFCON (if there are some) and which of those have changed in gtkmvc.

Originally created by @Rbelder  at 2018-12-06 16:36:01+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
But I already talked to @franzlst and mentioned that the errors are not fully new. So forget this gtkmvc possibility we have this issues with basically the same tracebacks in 0.12.25, too. Sorry, it is already too late.

Originally created by @Rbelder  at 2018-12-06 16:42:59+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So lets do bisect for both cases and we may find the fastest solution to it. ;-)  But in my case not today.

Originally created by @Rbelder  at 2018-12-06 16:44:36+00:00 (moved from RMC internal repository)
