### ISSUE TITLE
Statemachines modified with python2 and python3 cannot be opened by python2

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#641]
Steps to reproduce:

- create state machine in python 2
- add data flow from port of type bool to port of type object
- open state machine in python 3
- resave state machine in python 3
- open state machine in python 2
- notice that the data port of type object has now type 'future.types.newobject.newobject'
- following errors occur: `RecoveryModeException: DataFlow invalid within state "State x" (id DABJIG): Data flow (id: 6) with origin state "State x" (from data port name: input_1) and target state "State z" (to data port name: input_2) do not have matching data types (from '<type 'bool'>' to '<class 'future.types.newobject.newobject'>')`
- the state machine can of course be opened as RecoveryModeExceptions of this type are caught
- now resave the state machine with python 2
- now try to load state machine in python 2 again
- state machine cannot be loaded as json conversion fails with the following error message:

> Traceback (most recent call last):
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/backup/session.py", line 143, in restore_session_from_runtime_config
>     state_machine = storage.load_state_machine_from_path(path)
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/utils/timer.py", line 13, in func_wrapper
>     return_value = func(*args, **kwargs)
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/storage/storage.py", line 349, in load_state_machine_from_path
>     dirty_states=dirty_states)
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/storage/storage.py", line 449, in load_state_recursively
>     child_state = load_state_recursively(state, child_state_path, dirty_states)
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/storage/storage.py", line 397, in load_state_recursively
>     state_info = load_data_file(path_core_data)
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/storage/storage.py", line 478, in load_data_file
>     return storage_utils.load_objects_from_json(path_of_file)
>   File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/utils/storage_utils.py", line 124, in load_objects_from_json
>     result = json.load(f, cls=JSONObjectDecoder, substitute_modules=substitute_modules)
>   File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
>     **kw)
>   File "/usr/lib64/python2.7/json/__init__.py", line 352, in loads
>     return cls(encoding=encoding, **kw).decode(s)
>   File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
>     obj, end = self.scan_once(s, idx)
>   File "/home_local/sebastian-brunner/develop/python-jsonconversion/src/jsonconversion/decoder.py", line 76, in _dict_to_qualified_object
>     return string2type(dictionary['__type__'])
>   File "/home_local/sebastian-brunner/develop/python-jsonconversion/src/jsonconversion/conversion.py", line 44, in string2type
>     return get_class_from_qualified_name(string_value)
>   File "/home_local/sebastian-brunner/develop/python-jsonconversion/src/jsonconversion/conversion.py", line 82, in get_class_from_qualified_name
>     cls = getattr(cls, comp)
> AttributeError: type object 'newobject' has no attribute 'newobject'

To fix the RecoveryModeException we have to handle `future.types.newobject.newobject` like `object`.

The jsonconversion error is a little bit creepy: `future.types.newobject.newobject` is definitely a type which exists both in python2 and python3

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-12-10 07:55:08+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I think I should fix this directly in `jsonconversion`

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-10 07:57:43+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So it was a stupid typo is `jsonconversion`. It is fixed, a new release is publsihed and RAFCON depends on this as minimum version.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2018-12-10 08:38:59+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Nice. :+1: 

Originally created by @Rbelder  at 2018-12-10 08:42:06+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Thx for the fast reply!

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-12-10 12:39:48+00:00 (moved from RMC internal repository)
