### ISSUE TITLE
crash in load_state_machine

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#658]
When loading specific state machines racon crashes.

It is not related to the modification history, as I can disable it and the error still occurs.

It is related to the refactor_income_handling, as commit 147e3bd7e45eed6151c3804f88af2d3e443efeea still works but e4c3c4c960fdfae8d1f8346aca03b12beff7772c does not.

Example stack trace:

2019-01-08 09:51:24:    ERROR - rafcon.gui.models.state_machine_manager:  An 'AttributeError' exception was raised in the core. Details about the origin:
	'after': True
	'model': <rafcon.gui.models.state_machine_manager.StateMachineManagerModel object at 0x7ff8b10f7d10>
	'prop_name': state_machine_manager
	'instance': <rafcon.core.state_machine_manager.StateMachineManager object at 0x7ff8b1234f10>
	'method_name': add_state_machine
	'args': (<rafcon.core.state_machine_manager.StateMachineManager object at 0x7ff8b1234f10>, <rafcon.core.state_machine.StateMachine object at 0x7ff89417edd0>)
	'kwargs': {}
	'result': 'NoneType' object has no attribute 'meta'
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 48, in wrapper
    self._notify_method_after(self, _func.__name__, res, args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/support/wrappers.py", line 84, in _notify_method_after
    args, kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 746, in notify_method_after_change
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 71, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 593, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine_manager.py", line 95, in model_changed
    self.state_machines[sm_id] = StateMachineModel(sm)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state_machine.py", line 77, in __init__
    self.root_state = ContainerStateModel(root_state, parent=self, load_meta_data=load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/container_state.py", line 62, in __init__
    self._load_child_state_models(load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/container_state.py", line 86, in _load_child_state_models
    self._add_model(self.states, child_state, model_class, child_state.state_id, load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state.py", line 244, in _add_model
    load_meta_data=load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 45, in __init__
    self.recursive_generate_models(load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 59, in recursive_generate_models
    self.initiate_library_root_state_model()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 79, in initiate_library_root_state_model
    self.state_copy = model_class(self.state.state_copy, parent=self)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/container_state.py", line 62, in __init__
    self._load_child_state_models(load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/container_state.py", line 86, in _load_child_state_models
    self._add_model(self.states, child_state, model_class, child_state.state_id, load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state.py", line 244, in _add_model
    load_meta_data=load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 45, in __init__
    self.recursive_generate_models(load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 59, in recursive_generate_models
    self.initiate_library_root_state_model()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 79, in initiate_library_root_state_model
    self.state_copy = model_class(self.state.state_copy, parent=self)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/container_state.py", line 62, in __init__
    self._load_child_state_models(load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/container_state.py", line 86, in _load_child_state_models
    self._add_model(self.states, child_state, model_class, child_state.state_id, load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/state.py", line 244, in _add_model
    load_meta_data=load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 45, in __init__
    self.recursive_generate_models(load_meta_data)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/library_state.py", line 69, in recursive_generate_models
    if not self.load_meta_data():
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/abstract_state.py", line 512, in load_meta_data
    self._parse_for_element_meta_data(tmp_meta)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/abstract_state.py", line 598, in _parse_for_element_meta_data
    self._copy_element_meta_data_from_meta_file_data(meta_data, self.income, "income", "")
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/abstract_state.py", line 615, in _copy_element_meta_data_from_meta_file_data
    element_m.meta = meta_data_element
AttributeError: 'NoneType' object has no attribute 'meta'
2019-01-08 09:51:24:    ERROR - rafcon.gui.helpers.state_machine:  Error while trying to open state machine: 'NoneType' object has no attribute 'meta'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-08 08:55:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
A state machine where the bug can reproduced is given here:

[pick_object_simulation.zip](https://rmc-github-server/common/rafcon/files/94/pick_object_simulation.zip)


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-08 09:06:51+00:00 (moved from RMC internal repository)
