### ISSUE TITLE
Error while deleting generated states

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#661]
error_message: ''
15:59:13 ERROR - core.states.execution_state: ExecutionState with name 'generate state' and id 'QRRWWV' had an internal error: AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
Traceback (most recent call last):
  File "script.py (5377)", line 63, in execute
  File "script.py (5377)", line 43, in call_gui_callback
  File "/internal_path/common/foreign_packages/python-gaphas/1.0.0rc1/osl42-x86_64/lib64/python2.7/site-packages/gi/__init__.py", line 72, in __getattr__
    raise AttributeError(_static_binding_error)
AttributeError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject". See: https://bugzilla.gnome.org/show_bug.cgi?id=709183
15:59:13 ERROR - core.states.execution_state: ExecutionState with name 'finally delete state' and id 'OJKIJV' had an internal error: AttributeError: State_id None does not exist
Traceback (most recent call last):
  File "script.py (5383)", line 49, in execute
  File "/internal_path/common/foreign_packages/python-gtkmvc3/1.0.1/lib/python2.7/site-packages/gtkmvc3/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
AttributeError: State_id None does not exist

Originally created by doem-an  at 2019-01-09 15:10:03+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The issue is moved to the plugin repo, see https://rmc-github-server/common/rafcon_execution_hooks_plugin/issues/6.

Originally created by @Rbelder  at 2019-01-09 15:53:08+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I know what it is, I will care about it. It is related with our on-the-fly state generation and deletion.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-09 16:33:16+00:00 (moved from RMC internal repository)
