### ISSUE TITLE
Failure occur while running hook of kind 'finished' -> 'NoneType' object has no attribute 'format_exc' Traceback (most recent call last):

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#662]
16:10:31 ERROR - execution_hooks.execution_hooks_manager: Failure occur while running hook of kind 'finished' -> 'NoneType' object has no attribute 'format_exc'
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon_execution_hooks_plugin/0.1.2/lib/python2.7/execution_hooks/execution_hooks_manager.py", line 166, in run_hooks_of_kind
    state_machine_hook_script.execute(state=state, execution_kind=hook_kind)
  File "/internal_path/common/packages/rafcon_execution_hooks_plugin/0.1.2/lib/python2.7/execution_hooks/execution_hooks_script.py", line 58, in execute
    return execution_function(state, inputs, outputs, core_singleton.global_variable_manager, logger)
  File "hooks_script.py (5833)", line 108, in finished
  File "hooks_script.py (5833)", line 103, in stop_all
AttributeError: 'NoneType' object has no attribute 'format_exc'

Originally created by doem-an  at 2019-01-09 15:14:02+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Error of execution hooks plugin => @Rbelder: Is it fixed but not released?

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2019-01-09 15:20:40+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Ok I will do a new release 0.2.0 with the current repo which is gtk3 compatible and we investigate the error. further and maybe patch the plugin once more.

Originally created by @Rbelder  at 2019-01-09 15:33:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The issue is moved to the plugin repo, see https://rmc-github-server/common/rafcon_execution_hooks_plugin/issues/7.

Originally created by @Rbelder  at 2019-01-09 15:51:47+00:00 (moved from RMC internal repository)
