### ISSUE TITLE
cannot rename connected data_port

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#663]
A target data port of type "int", which is already connected to a source data port of type "object" cannot be renamed.

Stack trace:

Error while trying to change data port name
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/state_editor/io_data_port_list.py", line 254, in _apply_new_data_port_name
    self.state_data_port_dict[data_port_id].name = new_name
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/decorators.py", line 53, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/state_elements/data_port.py", line 150, in name
    self._change_property_with_validity_check('_name', name)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/decorators.py", line 53, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/core/state_elements/state_element.py", line 184, in _change_property_with_validity_check
    raise ValueError("The {2}'s '{0}' could not be changed: {1}".format(property_name[1:], message, class_name))
ValueError: The InputDataPort's 'name' could not be changed: Connection of two non-compatible data types

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-09 16:05:31+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Rename should not cause a validity check. My opinion is if this happens the implementation is not proper.

Originally created by @Rbelder  at 2019-01-10 10:28:14+00:00 (moved from RMC internal repository)
