### ISSUE TITLE
error message when connecting data flow

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#666]
Sometimes, non-deterministically, when adding a data flow, the following error message occurs. However the dataflow is nevertheless created.

08:11:46 INFO - gui.models.modification_history: Active Action states is interrupted and removed.
08:11:46 ERROR - gui.mygaphas.utils.gap_helper: Data flow couldn't be added: DataFlow invalid within state "pick objects and place on robot" (id DQLSTD): Exactly the same data flow is already existing -> Data flow - from_state: EINODI, from_port_key: 0, from_port_name: object_id, to_state: AHJDMO, to_port_key: 0, to_port_name: parent_id, data_flow_id: 8
08:11:47 ERROR - gui.controllers.graphical_editor_gaphas: Error while trying to emit meta data signal 'NoneType' object has no attribute 'state_machine' Model of state: HierarchyState with name 'pick objects and place on robot' and id 'DQLSTD' [10 child states]
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 682, in state_machine_change_after
    self._meta_data_changed(None, model, 'append_to_last_change', True)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 316, in _meta_data_changed
    model.meta_signal.emit(msg)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 97, in emit
    model.notify_signal_emit(name, arg)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 776, in notify_signal_emit
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 71, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 593, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/abstract_state.py", line 438, in meta_changed
    self.parent.meta_changed(model, prop_name, info)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/abstract_state.py", line 445, in meta_changed
    self.meta_signal.emit(msg)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 97, in emit
    model.notify_signal_emit(name, arg)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 776, in notify_signal_emit
    self, prop_name, info)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 71, in __notify_observer__
    *args, **kwargs)
  File "/home_local/sebastian-brunner/develop/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 593, in __notify_observer__
    return method(*args, **kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/models/modification_history.py", line 527, in meta_changed_notify_after
    self.active_action.after_storage = self.active_action.get_storage()
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/action.py", line 547, in get_storage
    state_tuple = get_state_tuple(self.state_machine_model.state_machine.get_state_by_path(self.parent_path))
AttributeError: 'NoneType' object has no attribute 'state_machine'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-11 07:14:15+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
It seems to be a timing issue. If the computer is under heavy load and has to draw a lot of states (+ transitions, data flows) I can reproduce the error with 75% probability.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-11 07:23:59+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I cannot reproduce it currently, I will reopen it if I  can.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-16 09:45:56+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Further, I will take a look on options how this could happen. If the issue is reopen the traceback should include the actions before the traceback, too. With Andreas we also have had this problem that the traceback was too short to figure out all what happened.

Here the possibility is also there that the gaphas editor has had some timing issue.

The order of thinks in the trace back seems to be:
- tried generation of already existing data flow
- failure traceback that the modification history let abort the action which currently is observed
- gaphas that updates the meta data and tells the modification history to append those to the last action (question why gaphas would change and append the meta data if there was no or an abort action?)
- finally the no more or not already fully initialized action trys to update its after state of meta data for already existing action


Originally created by @Rbelder  at 2019-01-16 09:57:05+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So the issue is still in. I wanted to check the gv option for default values  and got the traceback while drawing the data flow.

It looked like gaphas has drawn two data flows before I released the mouse button. As long as we no more have the creation of data flows in our logger messages this is only what I have seen. 

@franzlst  Can you please check if there is an possibility that gaphas creates two data flows in a row? It looks also asynchronous. 

I will have now a verbose logger message in add data flow in my code to observe this. The error is very nondeterministic.

```
17:16:24 DEBUG - gui.models.auto_backup: Performing auto backup of state machine 1 to temp folder
17:16:24 DEBUG - core.storage.storage: State machine with id 1 was saved at /tmp/rafcon-Rbelder/24785/runtime_backup/not_stored_1
17:17:04 DEBUG - core.global_variable_manager: Global variable 'new_global_0' was set to value 'None' with type 'NoneType'
17:17:07 DEBUG - core.global_variable_manager: Global variable new_global_0 was deleted!
17:17:07 DEBUG - core.global_variable_manager: Global variable 'Rico' was set to value 'None' with type 'NoneType'
17:17:12 WARNING - gui.controllers.global_variable_manager: Old value 'None' of global variable 'Rico' could not be parsed to new type 'float' and is therefore resetted: float() argument must be a string or a number
17:17:12 DEBUG - core.global_variable_manager: Global variable 'Rico' was set to value '0.0' with type 'float'
17:17:15 DEBUG - core.global_variable_manager: Global variable 'Rico' was set to value '2.0' with type 'float'
17:17:18 DEBUG - gui.models.auto_backup: Performing auto backup of state machine 1 to temp folder
17:17:18 DEBUG - core.storage.storage: State machine with id 1 was saved at /tmp/rafcon-Rbelder/24785/runtime_backup/not_stored_1
17:17:41 DEBUG - gui.models.auto_backup: Performing auto backup of state machine 1 to temp folder
17:17:41 DEBUG - core.storage.storage: State machine with id 1 was saved at /tmp/rafcon-Rbelder/24785/runtime_backup/not_stored_1
17:18:32 DEBUG - gui.controllers.state_editor.source_editor: Parsing execute script...
17:18:33 DEBUG - gui.controllers.utils.editor: The source was saved SourceEditorController.
17:18:47 INFO - gui.models.modification_history: Active Action states is interrupted and removed.
17:18:47 ERROR - gui.mygaphas.utils.gap_helper: Data flow couldn't be added: DataFlow invalid within state "Untitled" (id GZFXEB): Exactly the same data flow is already existing -> Data flow - from_state: GZFXEB, from_port_key: 0, from_port_name: input_0, to_state: NRDKUZ, to_port_key: 0, to_port_name: in, data_flow_id: 2
17:18:48 ERROR - gui.controllers.graphical_editor_gaphas: Error while trying to emit meta data signal 'NoneType' object has no attribute 'state_machine' Model of state: HierarchyState with name 'Untitled' and id 'GZFXEB' [1 child states]
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 625, in state_machine_change_after
    self._meta_data_changed(None, model, 'append_to_last_change', True)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 313, in _meta_data_changed
    model.meta_signal.emit(msg)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 97, in emit
    model.notify_signal_emit(name, arg)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 784, in notify_signal_emit
    self, prop_name, info)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 71, in __notify_observer__
    *args, **kwargs)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 601, in __notify_observer__
    return method(*args, **kwargs)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/abstract_state.py", line 438, in meta_changed
    self.parent.meta_changed(model, prop_name, info)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/abstract_state.py", line 445, in meta_changed
    self.meta_signal.emit(msg)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 97, in emit
    model.notify_signal_emit(name, arg)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 784, in notify_signal_emit
    self, prop_name, info)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 71, in __notify_observer__
    *args, **kwargs)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 601, in __notify_observer__
    return method(*args, **kwargs)
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/models/modification_history.py", line 527, in meta_changed_notify_after
    self.active_action.after_storage = self.active_action.get_storage()
  File "/net/notos/home_local/dark_room/taskcontrol/source/rafcon/gui/action.py", line 547, in get_storage
    state_tuple = get_state_tuple(self.state_machine_model.state_machine.get_state_by_path(self.parent_path))
AttributeError: 'NoneType' object has no attribute 'state_machine'
17:19:08 DEBUG - gui.models.auto_backup: Performing auto backup of state machine 1 to temp folder
17:19:08 DEBUG - core.storage.storage: State machine with id 1 was saved at /tmp/rafcon-Rbelder/24785/runtime_backup/not_stored_1
```


Originally created by @Rbelder  at 2019-01-16 16:51:26+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
And I could reproduce multiple data flow creation at least. Sometimes one of them is no more in afterwards but sometimes there is a traceback like before. Here at least the one with two data flow generations  with additional verbose logger message.

```
17:43:13 INFO - gui.helpers.state_machine: It took 0.1s to load 3 states with 3 hierarchy levels.
17:43:13 VERBOSE - gui.controllers.graphical_editor_gaphas: start setup canvas
17:43:13 VERBOSE - gui.controllers.graphical_editor_gaphas: Time spent in setup canvas 0.0187978744507 state machine 3
17:43:23 VERBOSE - core.states.container_state: Add data flow from state_id 'GZFXEB' and port_id 0 to state_id 'NRDKUZ' and port_id 0 with id 1
17:43:24 INFO - gui.models.modification_history: This action has created a new branch in the state machine modification-history
17:43:28 VERBOSE - core.states.container_state: Add data flow from state_id 'GZFXEB' and port_id 0 to state_id 'NRDKUZ' and port_id 0 with id 2
17:43:34 VERBOSE - core.states.container_state: Add data flow from state_id 'GZFXEB' and port_id 0 to state_id 'NRDKUZ' and port_id 0 with id 3
17:43:54 DEBUG - gui.models.auto_backup: Performing auto backup of state machine 3 to temp folder
```

If I store this state machine the data flow with id 3 stays in.

Originally created by @Rbelder  at 2019-01-16 16:52:31+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
In combination with this twice in a row generation of identical data flows (even without traceback) I also get the problem (frequently) that I can no more remove this data flow via pressing delete on my keyboard. Maybe this gives some hint , too. But I think that is an issue with the shortcut manager because I can remove the data flow via the data flow widget in respective state editor and its remove button. 

So lets stay redundant with the edit options.

Originally created by @Rbelder  at 2019-01-16 16:58:16+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I can reproduce it now deterministically:

- open tutorial state machine: basic_turtle_demo (the bug is not related to this state machine, just an example)
- delete the transitions between "spawn turtle" and "Wait1"
- add the transition, and (before the transition "settled") immediately click on the target state "Wait1"


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-01-18 15:25:46+00:00 (moved from RMC internal repository)
