### ISSUE TITLE
External execution history log viewer not working

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#672]
So the gtk3 version has a problem to open the external execution log viewer. Here the traceback when I try to start it with the "Open externally" button from within the execution history widget.

2019-01-24 15:13:38:  VERBOSE - rafcon.gui.controllers.execution_log_viewer:  Select run_id: c7273d0e-1fde-11e9-ac90-64006a78a078.run_id.00000000000000000191
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.13.3/source/rafcon/gui/execution_log_viewer.py", line 24, in <module>
    log_tree_ctrl = SingleWidgetWindowController(model, single_view, ExecutionLogTreeController, args.file, args.run_id)
  File "/internal_path/common/packages/rafcon/0.13.3/source/rafcon/gui/controllers/utils/single_widget_window.py", line 34, in __init__
    self.add_controller('widget_ctrl', ctrl_class(model, view.get_top_widget(), *args, **kwargs))
  File "/internal_path/common/packages/rafcon/0.13.3/source/rafcon/gui/controllers/execution_log_viewer.py", line 37, in __init__
    self.hist_items = shelve.open(filename, 'r')
  File "/usr/lib64/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib64/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/lib64/python2.7/anydbm.py", line 79, in open
    raise error, "need 'c' or 'n' flag to open new db"
anydbm.error: need 'c' or 'n' flag to open new db

Originally created by @Rbelder  at 2019-01-24 14:17:44+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The stacktrace occurred, when the filepath passed to the viewer was wrong. I updated the error message.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-02-04 13:30:23+00:00 (moved from RMC internal repository)
