### ISSUE TITLE
script validation does not work

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#678]
When saving a script with code validation the following stacktrace occurs:

Using config file /home_local/sebastian-brunner/develop/rafcon/source/rafcon/pylintrc
2019-02-06 11:26:17:    ERROR - rafcon.gui.controllers.state_editor.source_editor:  Could not run linter to check script
Traceback (most recent call last):
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/gui/controllers/state_editor/source_editor.py", line 178, in apply_clicked
    lint.Run([self.tmp_file] + args, reporter=json_report, exit=False)
  File "/home/sebastian-brunner/.local/lib/python2.7/site-packages/pylint/lint.py", line 1348, in __init__
    linter.generate_reports()
  File "/home/sebastian-brunner/.local/lib/python2.7/site-packages/pylint/lint.py", line 1002, in generate_reports
    self.reporter.display_messages(report_nodes.Section())
  File "/home/sebastian-brunner/.local/lib/python2.7/site-packages/pylint/reporters/json.py", line 49, in display_messages
    print(json.dumps(self.messages, indent=4), file=self.out)
TypeError: unicode argument expected, got 'str'

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-02-06 10:28:04+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Thanks for fixing it. I have seen the bug yesterday already and before but never made it to write the issue.

Originally created by @Rbelder  at 2019-02-06 13:13:39+00:00 (moved from RMC internal repository)
