### ISSUE TITLE
Exception when sending a stop signal to RAFCON when execution is running

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#683]
Steps to reproduce:
1. Start RAFCON with PyCharm
2. Create a new state machine with just a root state
3. Run the state machine (it will not finish)
4. Hit the Stop button in PyCharm

Following traceback occurs:

```
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 198, in root_state_model_before_change
    self._send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 329, in _send_root_state_notification
    self.state_machine._notify_method_before(self.state_machine, cause, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_before'
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 212, in root_state_model_after_change
    self._send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 331, in _send_root_state_notification
    self.state_machine._notify_method_after(self.state_machine, cause, None, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_after'
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 198, in root_state_model_before_change
    self._send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 329, in _send_root_state_notification
    self.state_machine._notify_method_before(self.state_machine, cause, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_before'
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 212, in root_state_model_after_change
    self._send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 331, in _send_root_state_notification
    self.state_machine._notify_method_after(self.state_machine, cause, None, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_after'
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 198, in root_state_model_before_change
    self._send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 329, in _send_root_state_notification
    self.state_machine._notify_method_before(self.state_machine, cause, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_before'
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 212, in root_state_model_after_change
    self._send_root_state_notification(model, prop_name, info)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/models/state_machine.py", line 331, in _send_root_state_notification
    self.state_machine._notify_method_after(self.state_machine, cause, None, (self.state_machine, ), info)
AttributeError: 'NoneType' object has no attribute '_notify_method_after'
Traceback (most recent call last):
  File "/home_local/franzlst/gtkmvc/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home_local/franzlst/rafcon/source/rafcon/gui/controllers/state_machines_editor.py", line 538, in execution_engine_model_changed
    notebook = self.view['notebook']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2019-02-27 09:16:31+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
As I currently restructure the execution engine for some issues Rico found I will care about this.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-02-27 10:03:32+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
I think this is another issue Sebastian. But it could be this stopped_finished asynchronous behavior. 
Generally it is an notification loop which already has started and while this the editor is already destroyed. 

You can work around this bug by a check of `self._view_is_initialized` if false no more notifications are handled.
I have worked around this for the execution ticker, too.

Originally created by @Rbelder  at 2019-02-27 12:22:17+00:00 (moved from RMC internal repository)
