### ISSUE TITLE
Paste of Port into selected state is not possible

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#712]
It seems to be interrelated with the new income logical port which is not correctly handled in the clipboard right now.

I know about the issue already a while and never could try to solve it. Therefore here the reproduction procedure:
- generate a new state machine
- add a state and a input port to the root-state
- select the input port of the root state and copy it
- select the child state and try to paste the input port (to have two identical input ports in parent and child state)

And below the debug console output  which will be generated (DEBUG level True).

```
19:07:14 DEBUG - gui.models.selection: The selection has been reduced, as it may not contain elements whose children are also selected
19:07:20 INFO - gui.clipboard: The new content is 1 input data port
19:07:22 DEBUG - gui.controllers.graphical_editor_gaphas: Paste
19:07:22 ERROR - gui.shortcut_manager: Exception while calling callback methods for action "paste": 'income'
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.13.7/source/rafcon/gui/shortcut_manager.py", line 151, in trigger_action
    ret = callback_function(key_value, modifier_mask)
  File "/internal_path/common/packages/rafcon/0.13.7/source/rafcon/core/decorators.py", line 53, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/internal_path/common/packages/rafcon/0.13.7/source/rafcon/gui/controllers/graphical_editor_gaphas.py", line 254, in _paste_clipboard
    gui_helper_state_machine.paste_into_selected_state(self.model)
  File "/internal_path/common/packages/rafcon/0.13.7/source/rafcon/gui/helpers/state_machine.py", line 706, in paste_into_selected_state
    global_clipboard.paste(target_state_m)
  File "/internal_path/common/packages/rafcon/0.13.7/source/rafcon/gui/clipboard.py", line 208, in paste
    insert_elements_from_model_copies_list(element_m_copy_lists[state_element_attr],
KeyError: 'income'
```

Here also a test would be nice to secure this kind of basic functionality from now on.

Originally created by @Rbelder  at 2019-04-03 17:16:26+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Confirmed, already fixing it.

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2019-04-04 07:18:26+00:00 (moved from RMC internal repository)
