### ISSUE TITLE
race condition in state_machine_manager?

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#715]
Hello,
when i am using the first code snippet below, i get a keyError, as seen in the Stacktrace below. 
But when i sleep between both lines (as in the third snippet), everything is fine. So i thought there maybe a race condition in the state machine manager, or is my code wrong?

```python
        if state_machine_manager.is_state_machine_open(state_machine.file_system_path):
            old_sm = state_machine_manager.get_open_state_machine_of_file_system_path(state_machine.file_system_path)
            state_machine_manager.remove_state_machine(old_sm.state_machine_id)

        new_state_machine = storage.load_state_machine_from_path(state_machine_path)
        state_machine_manager.add_state_machine(new_state_machine)
```

```  
Traceback (most recent call last):
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 77, in __idle_callback
    method(*args, **kwargs)
  File "/home/CSuerig/USERSTORE/repositories/rafcon/source/rafcon/gui/models/state_machine_manager.py", line 109, in model_changed
    del self.state_machines[sm_id_to_delete]
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/support/wrappers.py", line 147, in __delitem__
    self._notify_method_after(self._obj, "__delitem__", res, (key,), {})
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/support/wrappers.py", line 84, in _notify_method_after
    args, kwargs)
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 746, in notify_method_after_change
    self, prop_name, info)
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/model_mt.py", line 71, in __notify_observer__
    *args, **kwargs)
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/model.py", line 593, in __notify_observer__
    return method(*args, **kwargs)
  File "/home/CSuerig/USERSTORE/repositories/rafcon/source/rafcon/gui/controllers/state_machines_editor.py", line 289, in model_changed
    self.add_graphical_state_machine_editor(self.model.state_machines[sm_id])
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/support/wrappers.py", line 151, in __getitem__
    return self._obj.__getitem__(key)
KeyError: 18

```
```python
        if state_machine_manager.is_state_machine_open(state_machine.file_system_path):
            old_sm = state_machine_manager.get_open_state_machine_of_file_system_path(state_machine.file_system_path)
            state_machine_manager.remove_state_machine(old_sm.state_machine_id)
        time.sleep(0.1)
        new_state_machine = storage.load_state_machine_from_path(state_machine_path)
        state_machine_manager.add_state_machine(new_state_machine)
```

Originally created by @CSuerig  at 2019-04-17 11:35:00+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The point is that you are working with the gui in the loop what you can see because there is gtkmvc3 in the traceback. I will be in the mobillab in the afternoon today. We can have a look at the specific example you are using but generally you have to use call_gui_callbacks to stay synchronous with the gui. Just import the following and apply it on any rafcon object generation.

`from rafcon.utils.gui_functions import call_gui_callback`

Originally created by @Rbelder  at 2019-04-17 12:15:08+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Ah, perfect! thanks for the fast reply, i think it fixed it. 
Can i also work with the code below?

```python
from gi.repository import Gdk
Gdk.threads_enter()
#do gui synchronous stuff here
Gdk.threads_leave()
```

Originally created by @CSuerig  at 2019-04-17 12:27:56+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
This is deprecated, see https://wiki.gnome.org/Projects/PyGObject/Threading

If you check our code in `test/gui`, you will find many examples for using multi threading and `call_gui_callback`

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2019-04-17 12:49:07+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
okay, thank you! 

Originally created by @CSuerig  at 2019-04-17 12:49:50+00:00 (moved from RMC internal repository)
