### ISSUE TITLE
States that have data-flows from its output to its input crashs gahpas while state type change

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#717]
The current the state type change of an existing ES with data flow between its own output and input results in the following log messages and traceback, see below reproduction procedure. 

**Reproduction procedure:**
- add new state machine
- add one state (ES1) to its root state
- add an input and an output port of both (integer type by default)
- use the data flow widget to add the only possible data flow or current develop (give me a minute after that)
- perform a state type change of the ES1 state

Afterwards the meta data seems to be screwed and the gaphas instance is no more usable.

```
2019-04-24 13:21:19:    DEBUG - rafcon.gui.helpers.state_machine:  Change type of State 'Untitled' from ExecutionState to HierarchyState
2019-04-24 13:21:19:  VERBOSE - rafcon.gui.models.abstract_state:  Observer already unregistered!
2019-04-24 13:21:19:     INFO - rafcon.gui.mygaphas.canvas:  The destruct of gaphas items has to be fixed!
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/decorators.py", line 144, in async_wrapper
    func(*args, **kwargs)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 621, in update
    self.update_now()
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/decorators.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 661, in update_now
    dirty_items = sort(self._dirty_items, reverse=True)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 527, in sort
    return self._tree.sort(items, index_key="_canvas_index", reverse=reverse)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/tree.py", line 208, in sort
    return sorted(nodes, key=attrgetter(index_key), reverse=reverse)
AttributeError: 'DataFlowView' object has no attribute '_canvas_index'
Traceback (most recent call last):
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/decorators.py", line 144, in async_wrapper
    func(*args, **kwargs)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 621, in update
    self.update_now()
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/decorators.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 661, in update_now
    dirty_items = sort(self._dirty_items, reverse=True)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/canvas.py", line 527, in sort
    return self._tree.sort(items, index_key="_canvas_index", reverse=reverse)
  File "/net/notos/home_local/dark_room/in_progress/rafcon/foreign_packages/repos/gaphas/gaphas/tree.py", line 208, in sort
    return sorted(nodes, key=attrgetter(index_key), reverse=reverse)
AttributeError: 'DataFlowView' object has no attribute '_canvas_index'
...
```

The dots at the end mean that the traceback is often recursive. Often means mostly but not always. Further the number of cycles is not deterministic.

Originally created by @Rbelder  at 2019-04-24 11:37:19+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So the issue is not limited to the ES it exists for all state types.

Originally created by @Rbelder  at 2019-04-24 11:38:18+00:00 (moved from RMC internal repository)
