### ISSUE TITLE
Rafcon Crash on empty input port name

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#724]
When i tried to rename an input data port, of an execution state i had the field empty and hit return. Instead of rafcon telling me that an empty name is not possible it simply crashed with the following traceback:
```
Traceback (most recent call last):
  File "/home/CSuerig/USERSTORE/repositories/rafcon/source/rafcon/gui/controllers/state_editor/io_data_port_list.py", line 254, in _apply_new_data_port_name
    self.state_data_port_dict[data_port_id].name = new_name
  File "/home/CSuerig/USERSTORE/repositories/rafcon/source/rafcon/core/decorators.py", line 53, in func_wrapper
    return_value = func(*args, **kwargs)
  File "/home/CSuerig/USERSTORE/repositories/gtkmvc3/gtkmvco/gtkmvc3/observable.py", line 47, in wrapper
    res = _func(*args, **kwargs)
  File "/home/CSuerig/USERSTORE/repositories/rafcon/source/rafcon/core/state_elements/data_port.py", line 144, in name
    raise ValueError("Name cannot be empty")
ValueError: Name cannot be empty
```

Originally created by @CSuerig  at 2019-05-03 07:47:49+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Thank you for reporting this issue. However, I am not able to reproduce this. I am getting the error message (this is expected and a correct behaviour), but RAFCON does not crash but just resets the input port name.

Which version of RAFCON are you using? You seem to have your own local copy. Could you please try the latest version and see whether the error occurs there, too?

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2019-05-03 07:51:24+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The logger message should not be a traceback but the instance most important should not crash.

@CSuerig I tried to reproduce the failure you have and got the traceback but no crash. So please confirm that the RAFCON instance really crashed and that it was not only this kind of traceback.

**Note for the future**: Please copy and paste the console output which includes the lines before and after the traceback of interest to draw a full picture and finally to accelerate communication and also quality of response. Thanks.

Originally created by @Rbelder  at 2019-05-03 08:37:10+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
By the way that you get and `ValueError` with the message "Name cannot be empty" is not a failure this is telling you that you made an invalid insertion.

Originally created by @Rbelder  at 2019-05-03 08:40:17+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
In my case it was just crashing, but i am also not able to reproduce it anymore.  
I work with commit `91389edfb6c46b30867ac3e481744408475b1362` of the `development` branch. 
@Rbelder Thats a good idea, i will do this next time!
@Rbelder  Yes sure a `ValueError` is not a failure, but i thought the termination of rafcon as consequence of an invalid insertion is. 

Originally created by @CSuerig  at 2019-05-03 11:59:50+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
So after you have a hard time to reproduce now, too, the console-log could have been valuable. I think you most likely have had an already longer running instance and the crash could result out of another traceback or failure before. 

Currently i also have sometimes screwed instances (last released version) mostly not crashing but from the observed behavior my opinion is that other bugs that are not resolved or reported cause this problems. Hard to project this on the develop-branch. If I develop state machines for kontur I mostly use there environment what creates a bad situation for me as a developer.

Originally created by @Rbelder  at 2019-05-03 15:29:11+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Thx for the posting this issue. I will close it for now. Reopen it if it happens again and you can provide "Steps to reproduce".

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-05-09 06:30:47+00:00 (moved from RMC internal repository)
