### ISSUE TITLE
rafcon server not starting due to missing class rafcon.utils.storage_utils import StorageUtils

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#806]
The executed ln process is: 

```
cd /internal_path/common/packages/rafcon/latest/lib/python2.7/rafcon_server/mvc; /opt/python/python2.7/bin/python /internal_path/common/packages/rafcon/latest/lib/python2.7/rafcon_server/mvc/main.py -o /internal_path/moro/packages/statemachines/latest/spacebotcup/mission/qualification_task_1 -nc ~/rmc_launch/cfg
```

It outputs the error:

```
process rafcon_task1 started with pid 8368

20:00:49:     INFO - rafcon_server:  initialize RAFCON ... 
20:00:50:    DEBUG - rafcon.utils.config:  Configuration loaded from /home/f_mobil/.config/rafcon/config.yaml
20:00:50:    DEBUG - rafcon.statemachine.library_manager:  Initializing Storage object ...
20:00:50:    DEBUG - rafcon.statemachine.storage.storage:  Storage class initialized!
20:00:50:    DEBUG - rafcon.statemachine.execution.statemachine_status:  Statemachine status is set to STATE_MACHINE_EXECUTION_STATUS.STOPPED
20:00:50:    DEBUG - rafcon.statemachine.execution.statemachine_execution_engine:  Statemachine execution engine initialized
20:00:50:    DEBUG - rafcon.statemachine.storage.storage:  Storage class initialized!
Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/latest/lib/python2.7/rafcon_server/mvc/main.py", line 14, in <module>
    from rafcon_server.mvc.controller.debug_view import DebugViewController
  File "/internal_path/common/packages/rafcon/0.5.2/lib/python2.7/rafcon_server/mvc/controller/debug_view.py", line 6, in <module>
    from rafcon.utils.storage_utils import StorageUtils
ImportError: cannot import name StorageUtils

process with pid 8368 terminated with retval: 1

```

Originally created by SebastianRiedela  (Sebastian.Riedel@dlr.de) at 2015-11-05 19:04:54+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Fixed in commit 1304b7e (some time ago, by @sebastian-brunner )


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2015-11-26 07:34:43+00:00 (moved from RMC internal repository)
