### ISSUE TITLE
Fully integrate history with Gaphas

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#813]
Gaphas does not support all undo/redo operations from the GUI:
- state type changes need to pause notifications
- meta data must be kept

Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2015-11-09 15:25:18+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Undo of deletion operation also not working, here the traceback:

```
Traceback (most recent call last):
  File "/home_local/franzlst/taskcontrol/source/rafcon/mvc/controllers/state_machine_history.py", line 102, in on_undo_button_clicked
    self.undo(None, None)
  File "/home_local/franzlst/taskcontrol/source/rafcon/mvc/controllers/state_machine_history.py", line 136, in undo
    self._selected_sm_model.history.undo()
  File "/home_local/franzlst/taskcontrol/source/rafcon/mvc/history.py", line 820, in undo
    self.changes.undo()
  File "/internal_path/moro/packages/gtk_etc_python/0.0.5/sled11-x86_64-gcc4.x/lib/python2.7/site-packages/gtkmvc/observable.py", line 49, in wrapper
    res = _func(*args, **kwargs)
  File "/home_local/franzlst/taskcontrol/source/rafcon/mvc/history.py", line 1411, in undo
    self.trail_history[self.trail_pointer].undo()
  File "/home_local/franzlst/taskcontrol/source/rafcon/mvc/history.py", line 368, in undo
    self.set_state_to_version(state, self.before_storage)
  File "/home_local/franzlst/taskcontrol/source/rafcon/mvc/history.py", line 396, in set_state_to_version
    g_sm_editor._redraw()  # is used to secure update of graphical editor # TODO remove if not necessary anymore (private)
AttributeError: 'GraphicalEditorController' object has no attribute '_redraw'
```


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-01-11 15:24:58+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Deletion should be working as of commit d0b4ec7


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2016-01-11 15:32:52+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
General Core-Actions are working. 

Meta-Data changes that occur outside of GaphasEditor were not observed until commit 0b7017e780777d93ef0c4308e2a62f98325b2324. I could not connect the observation with the right functions in the GaphasEditor. The change of meta-data outside of the editor should be handled generally, see issue  #40. 

Test are running except of last change-history test and the GUI-Menu-Bar test.
-> GUI-Menu-Bar test crashes because of some drawing problem which aborts the action:
Traceback (most recent call last):
  File "/home/Rbelder/.local/lib/python2.7/site-packages/gaphas-0.7.2-py2.7.egg/gaphas/canvas.py", line 675, in update_now
    self.update_constraints(dirty_matrix_items)
  File "/home/Rbelder/.local/lib/python2.7/site-packages/gaphas-0.7.2-py2.7.egg/gaphas/canvas.py", line 772, in update_constraints
    self._solver.solve()
  File "/home/Rbelder/.local/lib/python2.7/site-packages/gaphas-0.7.2-py2.7.egg/gaphas/solver.py", line 620, in solve
    c.solve_for(wvar)
  File "/home_local/dark_room/taskcontrol/source/rafcon/mvc/mygaphas/constraint.py", line 48, in solve_for
    child_width = self.child_se[0].value - self.child_nw[0].value
  File "/home/Rbelder/.local/lib/python2.7/site-packages/gaphas-0.7.2-py2.7.egg/gaphas/canvas.py", line 1013, in __getitem__
    return self.pos[key]
  File "/home/Rbelder/.local/lib/python2.7/site-packages/gaphas-0.7.2-py2.7.egg/gaphas/canvas.py", line 1007, in <lambda>
    self._point, self._get_value(),
  File "/home/Rbelder/.local/lib/python2.7/site-packages/gaphas-0.7.2-py2.7.egg/gaphas/canvas.py", line 1003, in _get_value
    self._px, self._py = item.canvas.get_matrix_i2c(item).transform_point(x, y)
- the history test may crash because of not fully secure handled selections in Gaphas (while the StatesEditor is checked):

Traceback (most recent call last):
  File "/home_local/dark_room/taskcontrol/source/rafcon/utils/log.py", line 160, in wrapper
    return function(_args, *_kwargs)
  File "/home_local/dark_room/taskcontrol/source/test/common/testing_utils.py", line 72, in fun
    callback(_args)
  File "/net/notos/home_local/dark_room/gtkmvc_dlr/gtkmvc/observable.py", line 53, in wrapper
    self._notify_method_after(self, _func.__name__, e, args, kwargs)
  File "/net/notos/home_local/dark_room/gtkmvc_dlr/gtkmvc/support/wrappers.py", line 70, in _notify_method_after
    args, kwargs)
  File "/net/notos/home_local/dark_room/gtkmvc_dlr/gtkmvc/model.py", line 574, in notify_method_after_change
    self, prop_name, info)
  File "/net/notos/home_local/dark_room/gtkmvc_dlr/gtkmvc/model_mt.py", line 73, in __notify_observer__
    *args, *_kwargs)
  File "/net/notos/home_local/dark_room/gtkmvc_dlr/gtkmvc/model.py", line 467, in **notify_observer**
    return method(_args, *_kwargs)
  File "/home_local/dark_room/taskcontrol/source/rafcon/mvc/controllers/graphical_editor_gaphas.py", line 470, in selection_change
    self.handle_selected_states(info['args'][0].get_states())
  File "/home_local/dark_room/taskcontrol/source/rafcon/mvc/controllers/graphical_editor_gaphas.py", line 477, in handle_selected_states
    state_v.selected = True
AttributeError: 'NoneType' object has no attribute 'selected'


Originally created by @Rbelder  at 2016-01-28 10:15:34+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The issue seems also to be solved. If anybody has still problems and knows inconsistencies while using gaphas and the modification history together please report those. I will close the issue otherwise in latest a week.

Originally created by @Rbelder  at 2017-06-09 15:08:29+00:00 (moved from RMC internal repository)
