### ISSUE TITLE
Transition - when connection to wrong port -> error

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#822]
Connected data port with income of sibling state and then pressed escape key, lead to shitty behavior

Traceback (most recent call last):
  File "/internal_path/common/packages/rafcon/0.5.5/lib/python2.7/rafcon/mvc/controllers/graphical_editor.py", line 247, in _on_expose_event
    redraw = self.draw_state(self.root_state_m)
  File "/internal_path/common/packages/rafcon/0.5.5/lib/python2.7/rafcon/mvc/controllers/graphical_editor.py", line 1500, in draw_state
    redraw |= self.draw_state(child_state, child_rel_pos, child_size, depth + 1)
  File "/internal_path/common/packages/rafcon/0.5.5/lib/python2.7/rafcon/mvc/controllers/graphical_editor.py", line 1543, in draw_state
    self._handle_new_data_flow(state_m, depth)
  File "/internal_path/common/packages/rafcon/0.5.5/lib/python2.7/rafcon/mvc/controllers/graphical_editor.py", line 1813, in _handle_new_data_flow
    assert isinstance(self.single_selection, (DataPortModel, ScopedVariableModel))
AssertionError

Originally created by weit-ro  at 2015-11-27 10:15:35+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Fixed in commit #2cb7762


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2015-12-21 16:05:57+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Commit only fixed issues with transitions, not with data flows


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2015-12-21 16:07:44+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Fixed in commit #7d07804: Connection creation between logical and data ports are now forbidden.


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2015-12-21 16:36:53+00:00 (moved from RMC internal repository)
