### ISSUE TITLE
Shutdown error

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#824]
If step mode is activated and the state machine is closed, a pop window asks to stop the state machine before closing the GUI. If "stop state machine" is pressed, the GUI shuts down but the following error is procuded:

11:24:49:    DEBUG - rafcon.mvc.controllers.menu_bar:  Closing main window!
11:24:49:    DEBUG - rafcon.mvc.controllers.menu_bar:  Closing main window!
11:24:49:    DEBUG - rafcon.mvc.controllers.state_machine_tree:  expansion state of state machine None could not be stored
/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/state_machine_tree.py:126: GtkWarning: gtk_tree_store_get_path: assertion 'iter->stamp == tree_store->stamp' failed
  state_row_path = self.tree_store.get_path(state_row_iter)
Traceback (most recent call last):
  File "/internal_path/moro/packages/gtk_etc_python/0.0.4/sled11-x86_64-gcc4.x/lib/python2.7/site-packages/gtkmvc/model_mt.py", line 80, in __idle_callback
    method(_args, *_kwargs)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/main_window.py", line 383, in model_changed
    self.on_button_stop_shortcut_clicked(None)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/main_window.py", line 495, in on_button_stop_shortcut_clicked
    self.set_button_active(False, self.view['button_start_shortcut'], self.on_button_start_shortcut_toggled)
  File "/home_local/sebastian-brunner/develop/rafcon/source/rafcon/mvc/controllers/main_window.py", line 534, in set_button_active
    button.handler_block_by_func(func)
TypeError: nothing connected to <bound method MainWindowController.on_button_start_shortcut_toggled of <rafcon.mvc.controllers.main_window.MainWindowController object at 0x2c7bf90>>

The "closing main window" printed twice looks suspicious.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2015-11-30 10:27:06+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
This sounds like the `MenuBarController` uses the buttons to stop the state machine, but the GUI has already been destroyed.


Originally created by @franzlst  (Franz.Steinmetz@dlr.de) at 2015-11-30 10:46:11+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
after a state_machine is finished it does not actively stop the whole execution engine but just marks the executi


Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2015-11-30 14:08:59+00:00 (moved from RMC internal repository)
