### ISSUE TITLE
Error when trying BasicTurtleDemo

### ISSUE THREAD

**Issue by jeffRowley321** [DLR-RM/RAFCON#853]
Hi,
I tried to run the BasicTurtleDemo from the tutorials but I get this error:

```
15:34:36 ERROR - core.states.execution_state: ExecutionState with name 'init_ros_node' and id 'INIT_ROS_NODE' had an internal error: ModuleNotFoundError: No module named 'rospkg'
Traceback (most recent call last):
  File "script.py (2)", line 1, in <module>
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
```

**Comment by franzlst** [comment]
I think this is issue is not related to RAFCON, but ROS or your ROS environment. Googeling for "ModuleNotFoundError: No module named 'rospkg'" has the following two links as first two search hits:
* https://answers.ros.org/question/39657/importerror-no-module-named-rospkg/
* https://stackoverflow.com/questions/66554561/modulenotfounderror-no-module-named-rospkg
