### ISSUE TITLE
Failed to install on Ubuntu 20.04/python3/venv

### ISSUE THREAD

**Issue by vanem** [DLR-RM/RAFCON#866]
I tried to install RAFCON like this:

```
sudo apt instal python-is-python3
sudo apt install python3-venv
sudo apt install libgirepository1.0-dev #PyGObject ==3.30.0 fails to install otherwise
python -m venv venv/rafcon
source venv/rafcon/bin/activate
pip install wheel
pip install rafcon
```

`Successfully installed Automat-20.2.0 Jinja2-3.1.2 MarkupSafe-2.1.1 PyGObject-3.30.0 PyOpenGL-3.1.5 PyYAML-6.0 Pygments-2.12.0 Twisted-21.7.0 alabaster-0.7.12 astroid-2.8.5 attrs-21.4.0 babel-2.10.1 certifi-2022.5.18.1 charset-normalizer-2.0.12 click-8.1.3 click-default-group-1.2.2 constantly-15.1.0 cycler-0.11.0 docutils-0.17.1 gaphas-2.1.2 graphviz-0.20 hyperlink-21.0.0 idna-3.3 imagesize-1.3.0 importlib-metadata-1.7.0 incremental-21.3.0 isort-5.10.1 jsonconversion-0.2.13 lazy-object-proxy-1.7.1 matplotlib-2.1.1 mccabe-0.6.1 monitoring-0.9.12 numpy-1.19.5 objgraph-3.5.0 packaging-21.3 pandas-1.1.5 pillow-9.1.1 platformdirs-2.5.2 profiling-0.1.3 psutil-5.8.0 pyaes-1.6.1 pycairo-1.19.1 pykeyboard-0.1.2 pylint-2.11.1 pymouse-1.0 pyparsing-3.0.9 pyrogram-2.0.27 pysocks-1.7.1 python-dateutil-2.8.2 pytz-2022.1 rafcon-1.0.0 reportlab-3.6.10 requests-2.28.0 rst2pdf-0.98 setuptools-48.0.0 simplegeneric-0.8.1 six-1.16.0 smartypants-2.0.1 snowballstemmer-2.2.0 sphinx-4.3.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 tf-1.0.0 tgcrypto-1.2.3 toml-0.10.2 typing-extensions-4.2.0 urllib3-1.26.9 urwid-2.1.2 valuedispatch-0.0.1 wrapt-1.13.3 yaml-configuration-0.2.5 zipp-3.8.0 zope.interface-5.4.0`

In this env i try to run rafcon, but it fails to start:

```
Traceback (most recent call last):
  File "/home/vane/venv/rafcon/bin/rafcon", line 8, in <module>
    sys.exit(main())
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/start.py", line 436, in main
    setup_gui()
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/start.py", line 255, in setup_gui
    from rafcon.gui.controllers.main_window import MainWindowController
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/controllers/main_window.py", line 45, in <module>
    from rafcon.gui.controllers.states_editor import StatesEditorController
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/controllers/states_editor.py", line 30, in <module>
    from rafcon.gui.controllers.state_editor.state_editor import StateEditorController
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/controllers/state_editor/state_editor.py", line 33, in <module>
    from rafcon.gui.controllers.state_editor.source_editor import SourceEditorController
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/controllers/state_editor/source_editor.py", line 41, in <module>
    from rafcon.gui.views.state_editor.source_editor import SourceEditorView
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/rafcon/gui/views/state_editor/source_editor.py", line 16, in <module>
    from gi.repository import GtkSource
  File "/home/vane/venv/rafcon/lib/python3.8/site-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name GtkSource, introspection typelib not found
```

Some help please?

**Comment by franzlst** [comment]
Does the following thread help? https://stackoverflow.com/questions/21064163/what-do-i-have-to-install-to-resolve-could-not-find-any-typelib-for-gtksource-c
